packages:
  - 'apps/*'
  - 'modules/*'
  - 'packages/*'

savePrefix: ''
packageManagerStrictVersion: true
nodeVersion: 22.16.0
engineStrict: true
strictDepBuilds: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
