CREATE TABLE "product_categories" (
 "id" UUID NOT NULL, "company_id" UUID NOT NULL, "name" VARCHAR(120) NOT NULL, "normalized_name" VARCHAR(120) NOT NULL, "parent_id" UUID, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(6) NOT NULL,
 CONSTRAINT "product_categories_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "product_tags" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" VARCHAR(120) NOT NULL,"normalized_name" VARCHAR(120) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_tags_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_manufacturers" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" VARCHAR(180) NOT NULL,"normalized_name" VARCHAR(180) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_manufacturers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_ingredient_masters" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" VARCHAR(180) NOT NULL,"normalized_name" VARCHAR(180) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_ingredient_masters_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_dosage_forms" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" VARCHAR(120) NOT NULL,"normalized_name" VARCHAR(120) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_dosage_forms_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_routes" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" VARCHAR(120) NOT NULL,"normalized_name" VARCHAR(120) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_routes_pkey" PRIMARY KEY ("id"));
CREATE TABLE "central_drug_sources" ("id" UUID NOT NULL,"source_key" VARCHAR(120) NOT NULL,"name" VARCHAR(200) NOT NULL,"provenance" TEXT NOT NULL,"license_note" TEXT,"source_url" VARCHAR(500),"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "central_drug_sources_pkey" PRIMARY KEY ("id"));
CREATE TABLE "central_drug_datasets" ("id" UUID NOT NULL,"source_id" UUID NOT NULL,"dataset_key" VARCHAR(160) NOT NULL,"published_at" TIMESTAMPTZ(6),"ingested_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',CONSTRAINT "central_drug_datasets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "central_drug_references" ("id" UUID NOT NULL,"source_id" UUID NOT NULL,"dataset_id" UUID,"source_record_key" VARCHAR(180) NOT NULL,"canonical_name" VARCHAR(220) NOT NULL,"normalized_name" VARCHAR(220) NOT NULL,"arabic_name" VARCHAR(220),"normalized_arabic_name" VARCHAR(220),"english_name" VARCHAR(220),"normalized_english_name" VARCHAR(220),"trade_name" VARCHAR(220),"normalized_trade_name" VARCHAR(220),"manufacturer_name" VARCHAR(200),"dosage_form" VARCHAR(120),"route" VARCHAR(120),"regulatory_id" VARCHAR(120),"atc_code" VARCHAR(40),"prescription_class" VARCHAR(40),"controlled" BOOLEAN NOT NULL DEFAULT false,"package_description" VARCHAR(300),"base_unit_label" VARCHAR(80),"package_unit_label" VARCHAR(80),"conversion_factor" DECIMAL(18,6),"reference_price" DECIMAL(18,4),"market_status" VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',"source_effective_date" TIMESTAMPTZ(6),"last_verified_at" TIMESTAMPTZ(6),"status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',"version" INTEGER NOT NULL DEFAULT 1,"quarantine_reason" TEXT,"source_payload" JSONB,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "central_drug_references_pkey" PRIMARY KEY ("id"));
CREATE TABLE "products" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"product_code" VARCHAR(32) NOT NULL,"create_request_key" VARCHAR(120),"product_type" VARCHAR(20) NOT NULL,"display_name" VARCHAR(200) NOT NULL,"normalized_name" VARCHAR(200) NOT NULL,"arabic_name" VARCHAR(200),"normalized_arabic_name" VARCHAR(200),"english_name" VARCHAR(200),"normalized_english_name" VARCHAR(200),"trade_name" VARCHAR(200),"normalized_trade_name" VARCHAR(200),"description" TEXT,"notes" TEXT,"category_id" UUID,"manufacturer_id" UUID,"country_of_origin" VARCHAR(120),"dosage_form_id" UUID,"route_id" UUID,"regulatory_id" VARCHAR(120),"atc_code" VARCHAR(40),"prescription_class" VARCHAR(40),"controlled" BOOLEAN NOT NULL DEFAULT false,"cold_chain" BOOLEAN NOT NULL DEFAULT false,"storage_notes" TEXT,"market_status" VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',"reference_price" DECIMAL(18,4),"reference_price_source" VARCHAR(300),"reference_price_verified_at" TIMESTAMPTZ(6),"image_file_id" UUID,"central_reference_id" UUID,"central_snapshot" JSONB,"status" VARCHAR(20) NOT NULL DEFAULT 'DRAFT',"version" INTEGER NOT NULL DEFAULT 1,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "products_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_ingredient_assignments" ("id" UUID NOT NULL,"product_id" UUID NOT NULL,"ingredient_id" UUID NOT NULL,"strength_value" DECIMAL(18,6),"strength_unit" VARCHAR(40),"sort_order" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "product_ingredient_assignments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_units" ("id" UUID NOT NULL,"product_id" UUID NOT NULL,"name" VARCHAR(120) NOT NULL,"short_label" VARCHAR(40),"conversion_factor" DECIMAL(18,6) NOT NULL,"is_base" BOOLEAN NOT NULL DEFAULT false,"default_sale" BOOLEAN NOT NULL DEFAULT false,"default_purchase" BOOLEAN NOT NULL DEFAULT false,"active" BOOLEAN NOT NULL DEFAULT true,"version" INTEGER NOT NULL DEFAULT 1,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_units_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_barcodes" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"product_id" UUID NOT NULL,"unit_id" UUID NOT NULL,"value" VARCHAR(64) NOT NULL,"symbology" VARCHAR(30),"is_primary" BOOLEAN NOT NULL DEFAULT false,"active" BOOLEAN NOT NULL DEFAULT true,"source" VARCHAR(180),"version" INTEGER NOT NULL DEFAULT 1,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_barcodes_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_tag_assignments" ("id" UUID NOT NULL,"product_id" UUID NOT NULL,"tag_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "product_tag_assignments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_import_sessions" ("id" UUID NOT NULL,"kind" VARCHAR(20) NOT NULL,"scope_key" VARCHAR(80) NOT NULL,"company_id" UUID,"idempotency_key" VARCHAR(120) NOT NULL,"mode" VARCHAR(60) NOT NULL,"status" VARCHAR(20) NOT NULL DEFAULT 'OPEN',"source_name" VARCHAR(200),"source_id" UUID,"dataset_key" VARCHAR(160),"mapping" JSONB,"total_rows" INTEGER,"processed_rows" INTEGER NOT NULL DEFAULT 0,"accepted_rows" INTEGER NOT NULL DEFAULT 0,"updated_rows" INTEGER NOT NULL DEFAULT 0,"rejected_rows" INTEGER NOT NULL DEFAULT 0,"quarantined_rows" INTEGER NOT NULL DEFAULT 0,"created_by" UUID NOT NULL,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_import_sessions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "product_import_chunks" ("id" UUID NOT NULL,"session_id" UUID NOT NULL,"chunk_key" VARCHAR(120) NOT NULL,"status" VARCHAR(20) NOT NULL DEFAULT 'PROCESSING',"result" JSONB,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "product_import_chunks_pkey" PRIMARY KEY ("id"));
CREATE TABLE "central_drug_ingredients" ("id" UUID NOT NULL,"central_drug_id" UUID NOT NULL,"name" VARCHAR(180) NOT NULL,"normalized_name" VARCHAR(180) NOT NULL,"strength_value" DECIMAL(18,6),"strength_unit" VARCHAR(40),"sort_order" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "central_drug_ingredients_pkey" PRIMARY KEY ("id"));
CREATE TABLE "central_drug_barcodes" ("id" UUID NOT NULL,"central_drug_id" UUID NOT NULL,"value" VARCHAR(64) NOT NULL,"symbology" VARCHAR(30),CONSTRAINT "central_drug_barcodes_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "product_categories_company_id_normalized_name_key" ON "product_categories"("company_id","normalized_name");
CREATE INDEX "product_categories_company_id_active_idx" ON "product_categories"("company_id","active"); CREATE INDEX "product_categories_parent_id_idx" ON "product_categories"("parent_id");
CREATE UNIQUE INDEX "product_tags_company_id_normalized_name_key" ON "product_tags"("company_id","normalized_name"); CREATE INDEX "product_tags_company_id_active_idx" ON "product_tags"("company_id","active");
CREATE UNIQUE INDEX "product_manufacturers_company_id_normalized_name_key" ON "product_manufacturers"("company_id","normalized_name"); CREATE INDEX "product_manufacturers_company_id_active_idx" ON "product_manufacturers"("company_id","active");
CREATE UNIQUE INDEX "product_ingredient_masters_company_id_normalized_name_key" ON "product_ingredient_masters"("company_id","normalized_name"); CREATE INDEX "product_ingredient_masters_company_id_active_idx" ON "product_ingredient_masters"("company_id","active");
CREATE UNIQUE INDEX "product_dosage_forms_company_id_normalized_name_key" ON "product_dosage_forms"("company_id","normalized_name"); CREATE INDEX "product_dosage_forms_company_id_active_idx" ON "product_dosage_forms"("company_id","active");
CREATE UNIQUE INDEX "product_routes_company_id_normalized_name_key" ON "product_routes"("company_id","normalized_name"); CREATE INDEX "product_routes_company_id_active_idx" ON "product_routes"("company_id","active");
CREATE UNIQUE INDEX "central_drug_sources_source_key_key" ON "central_drug_sources"("source_key");
CREATE UNIQUE INDEX "central_drug_datasets_source_id_dataset_key_key" ON "central_drug_datasets"("source_id","dataset_key"); CREATE INDEX "central_drug_datasets_source_id_ingested_at_idx" ON "central_drug_datasets"("source_id","ingested_at");
CREATE UNIQUE INDEX "central_drug_references_regulatory_id_key" ON "central_drug_references"("regulatory_id"); CREATE UNIQUE INDEX "central_drug_references_source_id_source_record_key_key" ON "central_drug_references"("source_id","source_record_key"); CREATE INDEX "central_drug_references_status_normalized_name_idx" ON "central_drug_references"("status","normalized_name"); CREATE INDEX "central_drug_references_normalized_arabic_name_idx" ON "central_drug_references"("normalized_arabic_name"); CREATE INDEX "central_drug_references_normalized_english_name_idx" ON "central_drug_references"("normalized_english_name"); CREATE INDEX "central_drug_references_normalized_trade_name_idx" ON "central_drug_references"("normalized_trade_name"); CREATE INDEX "central_drug_references_manufacturer_name_idx" ON "central_drug_references"("manufacturer_name"); CREATE INDEX "central_drug_references_atc_code_idx" ON "central_drug_references"("atc_code");
CREATE UNIQUE INDEX "products_company_id_product_code_key" ON "products"("company_id","product_code"); CREATE UNIQUE INDEX "products_company_id_create_request_key_key" ON "products"("company_id","create_request_key"); CREATE UNIQUE INDEX "products_company_id_regulatory_id_key" ON "products"("company_id","regulatory_id"); CREATE UNIQUE INDEX "products_company_id_central_reference_id_key" ON "products"("company_id","central_reference_id"); CREATE INDEX "products_company_id_status_updated_at_idx" ON "products"("company_id","status","updated_at"); CREATE INDEX "products_company_id_normalized_name_idx" ON "products"("company_id","normalized_name"); CREATE INDEX "products_company_id_normalized_arabic_name_idx" ON "products"("company_id","normalized_arabic_name"); CREATE INDEX "products_company_id_normalized_english_name_idx" ON "products"("company_id","normalized_english_name"); CREATE INDEX "products_company_id_normalized_trade_name_idx" ON "products"("company_id","normalized_trade_name"); CREATE INDEX "products_manufacturer_id_idx" ON "products"("manufacturer_id"); CREATE INDEX "products_category_id_idx" ON "products"("category_id"); CREATE INDEX "products_dosage_form_id_idx" ON "products"("dosage_form_id"); CREATE INDEX "products_route_id_idx" ON "products"("route_id"); CREATE INDEX "products_central_reference_id_idx" ON "products"("central_reference_id");
CREATE UNIQUE INDEX "product_ingredient_assignments_product_id_ingredient_id_key" ON "product_ingredient_assignments"("product_id","ingredient_id"); CREATE INDEX "product_ingredient_assignments_ingredient_id_idx" ON "product_ingredient_assignments"("ingredient_id");
CREATE INDEX "product_units_product_id_active_idx" ON "product_units"("product_id","active"); CREATE UNIQUE INDEX "product_units_one_active_base" ON "product_units"("product_id") WHERE "active" = true AND "is_base" = true; CREATE UNIQUE INDEX "product_units_one_active_default_sale" ON "product_units"("product_id") WHERE "active" = true AND "default_sale" = true; CREATE UNIQUE INDEX "product_units_one_active_default_purchase" ON "product_units"("product_id") WHERE "active" = true AND "default_purchase" = true;
CREATE UNIQUE INDEX "product_barcodes_company_id_value_key" ON "product_barcodes"("company_id","value"); CREATE INDEX "product_barcodes_product_id_active_idx" ON "product_barcodes"("product_id","active"); CREATE INDEX "product_barcodes_unit_id_idx" ON "product_barcodes"("unit_id"); CREATE UNIQUE INDEX "product_barcodes_one_active_primary" ON "product_barcodes"("product_id") WHERE "active" = true AND "is_primary" = true;
CREATE UNIQUE INDEX "product_tag_assignments_product_id_tag_id_key" ON "product_tag_assignments"("product_id","tag_id"); CREATE INDEX "product_tag_assignments_tag_id_idx" ON "product_tag_assignments"("tag_id");
CREATE UNIQUE INDEX "product_import_sessions_kind_scope_key_idempotency_key_key" ON "product_import_sessions"("kind","scope_key","idempotency_key"); CREATE INDEX "product_import_sessions_company_id_created_at_idx" ON "product_import_sessions"("company_id","created_at"); CREATE INDEX "product_import_sessions_kind_status_updated_at_idx" ON "product_import_sessions"("kind","status","updated_at");
CREATE UNIQUE INDEX "product_import_chunks_session_id_chunk_key_key" ON "product_import_chunks"("session_id","chunk_key"); CREATE INDEX "product_import_chunks_session_id_status_idx" ON "product_import_chunks"("session_id","status");
CREATE INDEX "central_drug_ingredients_central_drug_id_sort_order_idx" ON "central_drug_ingredients"("central_drug_id","sort_order"); CREATE INDEX "central_drug_ingredients_normalized_name_idx" ON "central_drug_ingredients"("normalized_name");
CREATE UNIQUE INDEX "central_drug_barcodes_value_key" ON "central_drug_barcodes"("value"); CREATE INDEX "central_drug_barcodes_central_drug_id_idx" ON "central_drug_barcodes"("central_drug_id");

ALTER TABLE "product_categories" ADD CONSTRAINT "product_categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "product_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "central_drug_datasets" ADD CONSTRAINT "central_drug_datasets_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "central_drug_sources"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "central_drug_references" ADD CONSTRAINT "central_drug_references_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "central_drug_sources"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "central_drug_references" ADD CONSTRAINT "central_drug_references_dataset_id_fkey" FOREIGN KEY ("dataset_id") REFERENCES "central_drug_datasets"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "products" ADD CONSTRAINT "products_manufacturer_id_fkey" FOREIGN KEY ("manufacturer_id") REFERENCES "product_manufacturers"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "products" ADD CONSTRAINT "products_dosage_form_id_fkey" FOREIGN KEY ("dosage_form_id") REFERENCES "product_dosage_forms"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "products" ADD CONSTRAINT "products_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "product_routes"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "products" ADD CONSTRAINT "products_central_reference_id_fkey" FOREIGN KEY ("central_reference_id") REFERENCES "central_drug_references"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "product_ingredient_assignments" ADD CONSTRAINT "product_ingredient_assignments_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "product_ingredient_assignments" ADD CONSTRAINT "product_ingredient_assignments_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "product_ingredient_masters"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "product_units" ADD CONSTRAINT "product_units_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "product_barcodes" ADD CONSTRAINT "product_barcodes_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "product_barcodes" ADD CONSTRAINT "product_barcodes_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "product_units"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "product_tag_assignments" ADD CONSTRAINT "product_tag_assignments_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "product_tag_assignments" ADD CONSTRAINT "product_tag_assignments_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "product_tags"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "product_import_chunks" ADD CONSTRAINT "product_import_chunks_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "product_import_sessions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "central_drug_ingredients" ADD CONSTRAINT "central_drug_ingredients_central_drug_id_fkey" FOREIGN KEY ("central_drug_id") REFERENCES "central_drug_references"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "central_drug_barcodes" ADD CONSTRAINT "central_drug_barcodes_central_drug_id_fkey" FOREIGN KEY ("central_drug_id") REFERENCES "central_drug_references"("id") ON DELETE CASCADE ON UPDATE CASCADE;
