import { Body, Controller, Get, Headers, Inject, Param, Patch, Post, Query, Req } from '@nestjs/common';
import { AuthorizationError, ValidationError } from '@elhafez/errors';
import { PERMISSION_CHECKER, type PermissionChecker } from '@elhafez/permissions/contracts';
import { RequirePermission, type AccessPrincipal } from '@elhafez/platform-contracts';
import { parseWithSchema } from '@elhafez/validation';
import { z } from 'zod';
import { ProductsService, type ProductMutationContext } from '../application/products.service';
import type { CentralApplySection, CentralImportRow, CompanyImportRow, MasterKind, ProductListQuery } from '../application/products.repository';

const uuid=z.string().uuid();const text=(max:number)=>z.string().max(max).nullable().optional();const boolText=z.enum(['true','false']);const intText=z.string().regex(/^\d+$/);
const ingredientSchema=z.object({ingredientId:uuid,strengthValue:z.union([z.string(),z.number()]).nullable().optional(),strengthUnit:text(40),sortOrder:z.number().int().min(0).optional()});
const unitSchema=z.object({name:z.string().min(1).max(120),shortLabel:text(40),conversionFactor:z.union([z.string(),z.number()]),isBase:z.boolean().optional(),defaultSale:z.boolean().optional(),defaultPurchase:z.boolean().optional(),active:z.boolean().optional()});
const barcodeSchema=z.object({value:z.string().min(1).max(64),unitRef:text(100),symbology:text(30),isPrimary:z.boolean().optional(),active:z.boolean().optional(),source:text(180)});
const productDraftSchema=z.object({productType:z.enum(['DRUG','NON_DRUG']),displayName:z.string().min(1).max(200),arabicName:text(200),englishName:text(200),tradeName:text(200),description:text(4000),notes:text(4000),categoryId:uuid.nullable().optional(),tagIds:z.array(uuid).max(100).optional(),manufacturerId:uuid.nullable().optional(),countryOfOrigin:text(120),dosageFormId:uuid.nullable().optional(),routeId:uuid.nullable().optional(),regulatoryId:text(120),atcCode:text(40),prescriptionClass:text(40),controlled:z.boolean().optional(),coldChain:z.boolean().optional(),storageNotes:text(1000),marketStatus:z.enum(['AVAILABLE','DISCONTINUED','UNKNOWN']).optional(),referencePrice:z.union([z.string(),z.number()]).nullable().optional(),referencePriceSource:text(300),referencePriceVerifiedAt:z.union([z.string().datetime(),z.date()]).nullable().optional(),imageFileId:uuid.nullable().optional(),ingredients:z.array(ingredientSchema).max(30).optional(),units:z.array(unitSchema).max(30).optional(),barcodes:z.array(barcodeSchema).max(100).optional()});
const createSchema=productDraftSchema.extend({activate:z.boolean().optional()});
const updateSchema=productDraftSchema.omit({units:true,barcodes:true}).partial().extend({version:z.number().int().min(1)});
const statusSchema=z.object({status:z.enum(['DRAFT','ACTIVE','INACTIVE','ARCHIVED']),version:z.number().int().min(1)});
const unitUpdateSchema=unitSchema.partial().extend({version:z.number().int().min(1)});
const barcodeUpdateSchema=barcodeSchema.omit({unitRef:true}).partial().extend({unitId:uuid.optional(),version:z.number().int().min(1)});
const masterKindSchema=z.enum(['category','tag','manufacturer','ingredient','dosage-form','route']);
const masterCreateSchema=z.object({name:z.string().min(1).max(180),parentId:uuid.nullable().optional()});const masterUpdateSchema=masterCreateSchema.extend({active:z.boolean()});
const companyImportStartSchema=z.object({mode:z.enum(['CREATE_ONLY','UPSERT_PRODUCT_CODE','UPSERT_BARCODE']),mapping:z.unknown().optional(),totalRows:z.number().int().min(1).max(1000000).nullable().optional(),sourceName:text(200)});
const companyImportRowSchema=z.object({row:z.number().int().min(1),productCode:text(32),displayName:z.string().min(1).max(200),productType:z.enum(['DRUG','NON_DRUG']),arabicName:text(200),englishName:text(200),tradeName:text(200),manufacturerName:text(180),categoryName:text(120),ingredientName:text(180),strengthValue:text(40),strengthUnit:text(40),dosageFormName:text(120),routeName:text(120),barcode:text(64),barcodeSymbology:text(30),baseUnitName:text(120),packageUnitName:text(120),packageFactor:text(40),regulatoryId:text(120),atcCode:text(40),prescriptionClass:text(40),controlled:z.boolean().optional(),coldChain:z.boolean().optional(),referencePrice:text(40),referencePriceSource:text(300),marketStatus:z.enum(['AVAILABLE','DISCONTINUED','UNKNOWN']).optional(),notes:text(4000)});
const chunkSchema=z.object({chunkKey:z.string().min(1).max(120),rows:z.array(companyImportRowSchema).min(1).max(500)});
const centralSourceSchema=z.object({sourceKey:z.string().min(1).max(120),name:z.string().min(1).max(200),provenance:z.string().min(1).max(4000),licenseNote:z.string().max(4000).nullable().optional(),sourceUrl:z.string().max(500).nullable().optional(),active:z.boolean().optional()});
const centralStartSchema=z.object({sourceId:uuid,datasetKey:z.string().min(1).max(160),publishedAt:z.coerce.date().nullable().optional(),mapping:z.unknown().optional(),totalRows:z.number().int().min(1).max(2000000).nullable().optional(),sourceName:text(200)});
const centralRowSchema=z.object({row:z.number().int().min(1),sourceRecordKey:z.string().min(1).max(180),canonicalName:z.string().min(1).max(220),arabicName:text(220),englishName:text(220),tradeName:text(220),manufacturerName:text(200),ingredientName:text(180),strengthValue:text(40),strengthUnit:text(40),dosageForm:text(120),route:text(120),regulatoryId:text(120),atcCode:text(40),prescriptionClass:text(40),controlled:z.boolean().optional(),packageDescription:text(300),baseUnitLabel:text(80),packageUnitLabel:text(80),conversionFactor:text(40),barcode:text(64),barcodeSymbology:text(30),referencePrice:text(40),marketStatus:z.enum(['AVAILABLE','DISCONTINUED','UNKNOWN']).optional(),sourceEffectiveDate:z.coerce.date().nullable().optional(),lastVerifiedAt:z.coerce.date().nullable().optional(),sourcePayload:z.unknown().optional()});
const centralChunkSchema=z.object({chunkKey:z.string().min(1).max(120),publishedAt:z.coerce.date().nullable().optional(),rows:z.array(centralRowSchema).min(1).max(500)});
const applySchema=z.object({version:z.number().int().min(1),sections:z.array(z.enum(['names','drug-profile','manufacturer','ingredients','packaging','barcodes','reference-price'])).min(1).max(7)});
const bulkSchema=z.object({productIds:z.array(uuid).min(1).max(5000),patch:z.object({categoryId:uuid.nullable().optional(),manufacturerId:uuid.nullable().optional(),status:z.enum(['DRAFT','ACTIVE','INACTIVE','ARCHIVED']).optional(),tagIds:z.array(uuid).max(100).optional()})});

type AuthRequest={user:AccessPrincipal};
@Controller('products')
export class ProductsController{
 constructor(private readonly service:ProductsService,@Inject(PERMISSION_CHECKER)private readonly permissionChecker:PermissionChecker){}
 @Get() @RequirePermission('products.view') list(@Headers('x-company-id') companyId:string|undefined,@Query('search')search?:string,@Query('status')status?:string,@Query('productType')productType?:string,@Query('categoryId')categoryId?:string,@Query('manufacturerId')manufacturerId?:string,@Query('ingredientId')ingredientId?:string,@Query('dosageFormId')dosageFormId?:string,@Query('controlled')controlled?:string,@Query('hasBarcode')hasBarcode?:string,@Query('linkedCentral')linkedCentral?:string,@Query('page')page?:string,@Query('pageSize')pageSize?:string){return this.service.list(this.listQuery(companyId,{search,status,productType,categoryId,manufacturerId,ingredientId,dosageFormId,controlled,hasBarcode,linkedCentral,page,pageSize}));}
 @Get('barcode/:barcode') @RequirePermission('products.view') barcode(@Param('barcode')barcode:string,@Headers('x-company-id')companyId:string|undefined){return this.service.resolveBarcode(this.company(companyId),barcode);}
 @Post('duplicates') @RequirePermission('products.view') duplicates(@Headers('x-company-id')companyId:string|undefined,@Body()body:unknown){return this.service.findLikelyDuplicates(this.company(companyId),parseWithSchema(productDraftSchema,body));}
 @Get('export') @RequirePermission('products.export') export(@Headers('x-company-id')companyId:string|undefined,@Query('format')format?:string,@Query('search')search?:string,@Query('status')status?:string,@Query('productType')productType?:string,@Query('categoryId')categoryId?:string,@Query('manufacturerId')manufacturerId?:string){const q=this.listQuery(companyId,{search,status,productType,categoryId,manufacturerId});const{page:_p,pageSize:_s,...filters}=q;return format==='xlsx'?this.service.exportTable(filters):this.service.exportCsv(filters);}
 @Post('bulk/preview') @RequirePermission('products.bulk-update') bulkPreview(@Headers('x-company-id')companyId:string|undefined,@Body()body:unknown){const input=parseWithSchema(bulkSchema,body);return this.service.previewBulk(this.company(companyId),input.productIds);}
 @Post('bulk') @RequirePermission('products.bulk-update') bulk(@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Headers('idempotency-key')key:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(bulkSchema,body);return this.service.bulkUpdate(input.productIds,input.patch,this.idempotency(key),this.context(companyId,branchId,requestId,req.user));}

 @Get('masters/:kind') @RequirePermission('products.view') masters(@Param('kind')kind:string,@Headers('x-company-id')companyId:string|undefined,@Query('includeInactive')include?:string){return this.service.listMasters(this.company(companyId),this.masterKind(kind),include==='true');}
 @Post('masters/:kind') @RequirePermission('products.manage-classification') createMaster(@Param('kind')kind:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(masterCreateSchema,body);return this.service.createMaster(this.masterKind(kind),input.name,input.parentId??null,this.context(companyId,branchId,requestId,req.user));}
 @Patch('masters/:kind/:id') @RequirePermission('products.manage-classification') updateMaster(@Param('kind')kind:string,@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(masterUpdateSchema,body);return this.service.updateMaster(this.masterKind(kind),parseWithSchema(uuid,id),input.name,input.active,input.parentId??null,this.context(companyId,branchId,requestId,req.user));}

 @Post('import/sessions') @RequirePermission('products.import') startImport(@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Headers('idempotency-key')key:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.startCompanyImport(parseWithSchema(companyImportStartSchema,body),this.idempotency(key),this.context(companyId,branchId,requestId,req.user));}
 @Get('import/sessions/:sessionId') @RequirePermission('products.import') importSession(@Param('sessionId')sessionId:string,@Headers('x-company-id')companyId:string|undefined){return this.service.getCompanyImportSession(parseWithSchema(uuid,sessionId),this.company(companyId));}
 @Post('import/sessions/:sessionId/chunks') @RequirePermission('products.import') importChunk(@Param('sessionId')sessionId:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(chunkSchema,body);return this.service.processCompanyImportChunk(parseWithSchema(uuid,sessionId),input.chunkKey,input.rows as CompanyImportRow[],this.context(companyId,branchId,requestId,req.user));}

 @Get('central/sources') @RequirePermission('products.central-catalog.view') centralSources(){return this.service.listCentralSources();}
 @Post('central/sources') @RequirePermission('products.central-catalog.manage') async createCentralSource(@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){await this.globalManage(req.user);const input=parseWithSchema(centralSourceSchema,body);return this.service.createCentralSource({...input,licenseNote:input.licenseNote??null,sourceUrl:input.sourceUrl??null,active:input.active??true},{actorId:req.user.userId,requestId:this.requestId(requestId)});}
 @Patch('central/sources/:id') @RequirePermission('products.central-catalog.manage') async updateCentralSource(@Param('id')id:string,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){await this.globalManage(req.user);const input=parseWithSchema(centralSourceSchema,body);return this.service.updateCentralSource(parseWithSchema(uuid,id),{...input,licenseNote:input.licenseNote??null,sourceUrl:input.sourceUrl??null,active:input.active??true},{actorId:req.user.userId,requestId:this.requestId(requestId)});}
 @Post('central/import/sessions') @RequirePermission('products.central-catalog.manage') async startCentralImport(@Headers('x-request-id')requestId:string|undefined,@Headers('idempotency-key')key:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){await this.globalManage(req.user);return this.service.startCentralImport(parseWithSchema(centralStartSchema,body),this.idempotency(key),{actorId:req.user.userId,requestId:this.requestId(requestId)});}
 @Post('central/import/sessions/:sessionId/chunks') @RequirePermission('products.central-catalog.manage') async centralChunk(@Param('sessionId')sessionId:string,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){await this.globalManage(req.user);const input=parseWithSchema(centralChunkSchema,body);return this.service.processCentralImportChunk(parseWithSchema(uuid,sessionId),input.chunkKey,input.rows as CentralImportRow[],input.publishedAt??null,{actorId:req.user.userId,requestId:this.requestId(requestId)});}
 @Get('central') @RequirePermission('products.central-catalog.view') central(@Query('search')search?:string,@Query('status')status?:string,@Query('manufacturer')manufacturer?:string,@Query('dosageForm')dosageForm?:string,@Query('controlled')controlled?:string,@Query('page')page?:string,@Query('pageSize')pageSize?:string){const q=parseWithSchema(z.object({search:z.string().max(220).optional(),status:z.enum(['ACTIVE','SUPERSEDED','RETIRED','QUARANTINED']).optional(),manufacturer:z.string().max(200).optional(),dosageForm:z.string().max(120).optional(),controlled:boolText.optional(),page:intText.optional(),pageSize:intText.optional()}),{search:search||undefined,status:status||undefined,manufacturer:manufacturer||undefined,dosageForm:dosageForm||undefined,controlled:controlled||undefined,page:page||undefined,pageSize:pageSize||undefined});return this.service.centralSearch({search:q.search,status:q.status,manufacturer:q.manufacturer,dosageForm:q.dosageForm,controlled:q.controlled===undefined?undefined:q.controlled==='true',page:this.queryInt(q.page,1,1,1000000),pageSize:this.queryInt(q.pageSize,25,1,100)});}
 @Get('central/:id') @RequirePermission('products.central-catalog.view') centralGet(@Param('id')id:string){return this.service.getCentral(parseWithSchema(uuid,id));}
 @Post('central/:id/adopt') @RequirePermission('products.central-catalog.use') adopt(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Headers('idempotency-key')key:string|undefined,@Req()req:AuthRequest){return this.service.adoptCentral(parseWithSchema(uuid,id),this.idempotency(key),this.context(companyId,branchId,requestId,req.user));}

 @Post() @RequirePermission('products.create') create(@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Headers('idempotency-key')key:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.create(parseWithSchema(createSchema,body),this.idempotency(key),this.context(companyId,branchId,requestId,req.user));}
 @Get(':id') @RequirePermission('products.view') get(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined){return this.service.get(this.company(companyId),parseWithSchema(uuid,id));}
 @Patch(':id') @RequirePermission('products.update') update(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.update(parseWithSchema(uuid,id),parseWithSchema(updateSchema,body),this.context(companyId,branchId,requestId,req.user));}
 @Patch(':id/status') @RequirePermission('products.change-status') status(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(statusSchema,body);return this.service.changeStatus(parseWithSchema(uuid,id),input.status,input.version,this.context(companyId,branchId,requestId,req.user));}
 @Post(':id/units') @RequirePermission('products.manage-units') addUnit(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.addUnit(parseWithSchema(uuid,id),parseWithSchema(unitSchema,body),this.context(companyId,branchId,requestId,req.user));}
 @Patch(':id/units/:unitId') @RequirePermission('products.manage-units') updateUnit(@Param('id')id:string,@Param('unitId')unitId:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.updateUnit(parseWithSchema(uuid,id),parseWithSchema(uuid,unitId),parseWithSchema(unitUpdateSchema,body),this.context(companyId,branchId,requestId,req.user));}
 @Post(':id/units/:unitId/deactivate') @RequirePermission('products.manage-units') deactivateUnit(@Param('id')id:string,@Param('unitId')unitId:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const{version}=parseWithSchema(z.object({version:z.number().int().min(1)}),body);return this.service.deactivateUnit(parseWithSchema(uuid,id),parseWithSchema(uuid,unitId),version,this.context(companyId,branchId,requestId,req.user));}
 @Post(':id/barcodes') @RequirePermission('products.manage-barcodes') addBarcode(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const parsed=parseWithSchema(barcodeSchema.extend({unitId:uuid}),body);const{unitId,...barcode}=parsed;return this.service.addBarcode(parseWithSchema(uuid,id),unitId,barcode,this.context(companyId,branchId,requestId,req.user));}
 @Patch(':id/barcodes/:barcodeId') @RequirePermission('products.manage-barcodes') updateBarcode(@Param('id')id:string,@Param('barcodeId')barcodeId:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){return this.service.updateBarcode(parseWithSchema(uuid,id),parseWithSchema(uuid,barcodeId),parseWithSchema(barcodeUpdateSchema,body),this.context(companyId,branchId,requestId,req.user));}
 @Post(':id/barcodes/:barcodeId/deactivate') @RequirePermission('products.manage-barcodes') deactivateBarcode(@Param('id')id:string,@Param('barcodeId')barcodeId:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const{version}=parseWithSchema(z.object({version:z.number().int().min(1)}),body);return this.service.deactivateBarcode(parseWithSchema(uuid,id),parseWithSchema(uuid,barcodeId),version,this.context(companyId,branchId,requestId,req.user));}
 @Get(':id/central-compare') @RequirePermission('products.central-catalog.use') compare(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Req()req:AuthRequest){return this.service.compareCentral(parseWithSchema(uuid,id),this.context(companyId,branchId,requestId,req.user));}
 @Post(':id/central-apply') @RequirePermission('products.central-catalog.use') apply(@Param('id')id:string,@Headers('x-company-id')companyId:string|undefined,@Headers('x-branch-id')branchId:string|undefined,@Headers('x-request-id')requestId:string|undefined,@Body()body:unknown,@Req()req:AuthRequest){const input=parseWithSchema(applySchema,body);return this.service.applyCentral(parseWithSchema(uuid,id),input.version,input.sections as CentralApplySection[],this.context(companyId,branchId,requestId,req.user));}

 private listQuery(companyId:string|undefined,input:Record<string,string|undefined>):ProductListQuery{const q=parseWithSchema(z.object({search:z.string().max(220).optional(),status:z.enum(['DRAFT','ACTIVE','INACTIVE','ARCHIVED']).optional(),productType:z.enum(['DRUG','NON_DRUG']).optional(),categoryId:uuid.optional(),manufacturerId:uuid.optional(),ingredientId:uuid.optional(),dosageFormId:uuid.optional(),controlled:boolText.optional(),hasBarcode:boolText.optional(),linkedCentral:boolText.optional(),page:intText.optional(),pageSize:intText.optional()}),{...input,search:input.search||undefined,status:input.status||undefined,productType:input.productType||undefined,categoryId:input.categoryId||undefined,manufacturerId:input.manufacturerId||undefined,ingredientId:input.ingredientId||undefined,dosageFormId:input.dosageFormId||undefined,controlled:input.controlled||undefined,hasBarcode:input.hasBarcode||undefined,linkedCentral:input.linkedCentral||undefined,page:input.page||undefined,pageSize:input.pageSize||undefined});return{companyId:this.company(companyId),search:q.search,status:q.status,productType:q.productType,categoryId:q.categoryId,manufacturerId:q.manufacturerId,ingredientId:q.ingredientId,dosageFormId:q.dosageFormId,controlled:q.controlled===undefined?undefined:q.controlled==='true',hasBarcode:q.hasBarcode===undefined?undefined:q.hasBarcode==='true',linkedCentral:q.linkedCentral===undefined?undefined:q.linkedCentral==='true',page:this.queryInt(q.page,1,1,1000000),pageSize:this.queryInt(q.pageSize,25,1,100)};}
 private queryInt(value:string|undefined,fallback:number,min:number,max:number){if(value===undefined)return fallback;const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new ValidationError('Invalid pagination query');return n;}
 private masterKind(v:string):MasterKind{return parseWithSchema(masterKindSchema,v);}
 private company(v:string|undefined){return parseWithSchema(uuid,v);}
 private idempotency(v:string|undefined){return parseWithSchema(z.string().min(8).max(120),v);}
 private requestId(v:string|undefined){return v?.slice(0,100);}
 private context(companyId:string|undefined,branchId:string|undefined,requestId:string|undefined,user:AccessPrincipal):ProductMutationContext{return{companyId:this.company(companyId),actorId:user.userId,branchId:branchId?parseWithSchema(uuid,branchId):undefined,requestId:this.requestId(requestId)};}
 private async globalManage(user:AccessPrincipal){if(user.platformAdmin)return;if(!(await this.permissionChecker.hasPermission(user.userId,'products.central-catalog.manage',{})))throw new AuthorizationError('Central catalog management requires GLOBAL permission');}
}
