export interface SpreadsheetTable { headers:string[]; rows:string[][]; }

function decodeXml(value:string):string{return value.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_m,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_m,n)=>String.fromCodePoint(Number.parseInt(String(n),16)));}
function parseCsv(text:string):SpreadsheetTable{const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i]??'';if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);const headers=(rows.shift()??[]).map((h,i)=>h.trim()||`Column ${i+1}`);return{headers,rows:rows.filter(r=>r.some(v=>v.trim()))};}
function colIndex(ref:string):number{const letters=(ref.match(/^[A-Z]+/i)?.[0]??'A').toUpperCase();let value=0;for(const ch of letters)value=value*26+(ch.charCodeAt(0)-64);return value-1;}
function u16(v:DataView,o:number){return v.getUint16(o,true);}function u32(v:DataView,o:number){return v.getUint32(o,true);}
async function inflateRaw(data:Uint8Array):Promise<Uint8Array>{const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function unzip(buffer:ArrayBuffer):Promise<Map<string,Uint8Array>>{const bytes=new Uint8Array(buffer);const view=new DataView(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(u32(view,i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('XLSX ZIP directory not found');const count=u16(view,eocd+10);let offset=u32(view,eocd+16);const decoder=new TextDecoder();const files=new Map<string,Uint8Array>();for(let i=0;i<count;i++){if(u32(view,offset)!==0x02014b50)throw new Error('Invalid XLSX ZIP directory');const method=u16(view,offset+10),compressed=u32(view,offset+20),nameLen=u16(view,offset+28),extraLen=u16(view,offset+30),commentLen=u16(view,offset+32),localOffset=u32(view,offset+42);const name=decoder.decode(bytes.slice(offset+46,offset+46+nameLen));if(u32(view,localOffset)!==0x04034b50)throw new Error('Invalid XLSX ZIP entry');const localNameLen=u16(view,localOffset+26),localExtraLen=u16(view,localOffset+28),start=localOffset+30+localNameLen+localExtraLen;const payload=bytes.slice(start,start+compressed);if(method===0)files.set(name,payload);else if(method===8)files.set(name,await inflateRaw(payload));else throw new Error(`Unsupported XLSX compression method ${method}`);offset+=46+nameLen+extraLen+commentLen;}return files;}
function parseSharedStrings(xml:string):string[]{return[...xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...(m[1]??'').matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(t=>decodeXml(t[1]??'')).join(''));}
function parseSheet(xml:string,shared:string[]):SpreadsheetTable{const rows:string[][]=[];for(const match of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const values:string[]=[];for(const cell of (match[1]??'').matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cell[1]??'',body=cell[2]??'',ref=/\br="([A-Z]+\d+)"/i.exec(attrs)?.[1]??`A${rows.length+1}`,type=/\bt="([^"]+)"/i.exec(attrs)?.[1]??'',raw=/<v>([\s\S]*?)<\/v>/.exec(body)?.[1]??'',inline=/<t\b[^>]*>([\s\S]*?)<\/t>/.exec(body)?.[1];const value=type==='s'?(shared[Number(raw)]??''):type==='inlineStr'?decodeXml(inline??''):type==='b'?(raw==='1'?'true':'false'):decodeXml(raw);values[colIndex(ref)]=value;}rows.push(values);}const headers=(rows.shift()??[]).map((h,i)=>h.trim()||`Column ${i+1}`);const width=headers.length;return{headers,rows:rows.filter(r=>r.some(v=>(v??'').trim())).map(r=>Array.from({length:width},(_,i)=>r[i]??''))};}
export async function parseSpreadsheet(file:File):Promise<SpreadsheetTable>{const lower=file.name.toLocaleLowerCase();if(lower.endsWith('.csv'))return parseCsv((await file.text()).replace(/^\uFEFF/,''));if(!lower.endsWith('.xlsx'))throw new Error('Only CSV and XLSX files are supported');const files=await unzip(await file.arrayBuffer());const decoder=new TextDecoder();const shared=files.get('xl/sharedStrings.xml');const sharedStrings=shared?parseSharedStrings(decoder.decode(shared)):[];const sheetName=[...files.keys()].filter(k=>/^xl\/worksheets\/sheet\d+\.xml$/i.test(k)).sort()[0];if(!sheetName)throw new Error('XLSX worksheet not found');return parseSheet(decoder.decode(files.get(sheetName)!),sharedStrings);}

function xml(value:string):string{return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function columnName(index:number):string{let n=index+1,out='';while(n){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26);}return out;}
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;})();
function crc32(bytes:Uint8Array):number{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&0xff]!^(c>>>8);return(c^0xffffffff)>>>0;}
function concat(parts:Uint8Array[]):Uint8Array{const length=parts.reduce((n,p)=>n+p.length,0);const out=new Uint8Array(length);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length;}return out;}
function le16(n:number){const a=new Uint8Array(2);new DataView(a.buffer).setUint16(0,n,true);return a;}function le32(n:number){const a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,n>>>0,true);return a;}
function zipStored(files:Array<{name:string;content:string}>):Uint8Array{const enc=new TextEncoder();const locals:Uint8Array[]=[];const centrals:Uint8Array[]=[];let offset=0;for(const file of files){const name=enc.encode(file.name),data=enc.encode(file.content),crc=crc32(data);const local=concat([le32(0x04034b50),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),name,data]);locals.push(local);centrals.push(concat([le32(0x02014b50),le16(20),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),le16(0),le16(0),le16(0),le32(0),le32(offset),name]));offset+=local.length;}const localBytes=concat(locals),centralBytes=concat(centrals),end=concat([le32(0x06054b50),le16(0),le16(0),le16(files.length),le16(files.length),le32(centralBytes.length),le32(localBytes.length),le16(0)]);return concat([localBytes,centralBytes,end]);}
export function createXlsx(table:SpreadsheetTable,sheetName='Products'):Blob{const all=[table.headers,...table.rows];const rows=all.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>`<c r="${columnName(c)}${r+1}" t="inlineStr"><is><t xml:space="preserve">${xml(value??'')}</t></is></c>`).join('')}</row>`).join('');const safeName=xml(sheetName.slice(0,31)||'Sheet1');const files=[{name:'[Content_Types].xml',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'},{name:'_rels/.rels',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},{name:'xl/workbook.xml',content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${safeName}" sheetId="1" r:id="rId1"/></sheets></workbook>`},{name:'xl/_rels/workbook.xml.rels',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'},{name:'xl/worksheets/sheet1.xml',content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows}</sheetData></worksheet>`}];return new Blob([zipStored(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
export function downloadBlob(blob:Blob,fileName:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
