import { useState } from 'react';
import type { FormEvent } from 'react';
import type { CentralDrugReferenceDetailView, CentralDrugReferenceView, CentralDrugSourceView } from '../../contracts';
import type { CentralDataset, ImportSession, Notice, RequestFn, Tri } from './types';
import { formatDate, nullable, showError } from './types';
import { TriSelect } from './ui';

export function CentralView({companyValid,central,search,setSearch,status,setStatus,manufacturer,setManufacturer,dosage,setDosage,strength,setStrength,controlled,setControlled,onPage,onAdopt,adoptedIds,detail,onDetail,sources,datasets,sessions,adminError,onLoadAdmin,globalRequest,onSources,notice}:{companyValid:boolean;central:{items:CentralDrugReferenceView[];page:number;pageSize:number;total:number};search:string;setSearch:(value:string)=>void;status:string;setStatus:(value:string)=>void;manufacturer:string;setManufacturer:(value:string)=>void;dosage:string;setDosage:(value:string)=>void;strength:string;setStrength:(value:string)=>void;controlled:Tri;setControlled:(value:Tri)=>void;onPage:(page?:number)=>Promise<void>;onAdopt:(reference:CentralDrugReferenceView)=>Promise<void>;adoptedIds:Set<string>;detail:CentralDrugReferenceDetailView|null;onDetail:(id:string)=>Promise<void>;sources:CentralDrugSourceView[];datasets:CentralDataset[];sessions:ImportSession[];adminError:string;onLoadAdmin:()=>Promise<void>;globalRequest:RequestFn;onSources:()=>Promise<void>;notice:(notice:Notice)=>void}){
 const[sourceForm,setSourceForm]=useState({sourceKey:'',name:'',provenance:'',licenseNote:'',sourceUrl:''});const[governNotes,setGovernNotes]=useState<Record<string,string>>({});
 async function createSource(event:FormEvent){event.preventDefault();try{await globalRequest('/products/central/sources',{method:'POST',body:JSON.stringify({...sourceForm,licenseNote:nullable(sourceForm.licenseNote),sourceUrl:nullable(sourceForm.sourceUrl),active:true})});setSourceForm({sourceKey:'',name:'',provenance:'',licenseNote:'',sourceUrl:''});await onSources();notice({kind:'success',text:'تم حفظ مصدر موثق'});}catch(error){showError(error,notice);}}
 async function govern(reference:CentralDrugReferenceView,next:'ACTIVE'|'SUPERSEDED'|'RETIRED'){const note=governNotes[reference.id]?.trim()??'';if(!note)return notice({kind:'error',text:'اكتب سبب/ملاحظة قرار الحوكمة'});try{await globalRequest(`/products/central-admin/references/${reference.id}/govern`,{method:'PATCH',body:JSON.stringify({version:reference.version,status:next,resolutionNote:note})});setGovernNotes(current=>({...current,[reference.id]:''}));await onPage(central.page);notice({kind:'success',text:'تم تنفيذ قرار الحوكمة وتسجيله في Audit'});}catch(error){showError(error,notice);}}
 return <section><div className="toolbar sticky"><input className="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="باركود / اسم / مادة فعالة / EDA / ATC"/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">Active trusted</option><option value="ACTIVE">ACTIVE</option><option value="SUPERSEDED">SUPERSEDED</option><option value="RETIRED">RETIRED</option><option value="QUARANTINED">QUARANTINED</option></select><input value={manufacturer} onChange={event=>setManufacturer(event.target.value)} placeholder="الشركة"/><input value={dosage} onChange={event=>setDosage(event.target.value)} placeholder="الشكل الدوائي"/><input value={strength} onChange={event=>setStrength(event.target.value)} placeholder="التركيز"/><TriSelect label="مراقب" value={controlled} onChange={setControlled}/><button onClick={()=>void onPage(1)}>تحديث</button></div>
  <div className="central-grid">{central.items.map(reference=><article key={reference.id} className={reference.status==='QUARANTINED'?'quarantined':''}><div className="central-title"><div><h3>{reference.canonicalName}</h3><p>{reference.manufacturerName||'—'} · {reference.dosageForm||'—'} · {reference.packageDescription||'—'}</p></div><span className={`status ${reference.status.toLowerCase()}`}>{reference.status}</span></div><p>{reference.ingredients.map(item=>`${item.name}${item.strengthValue?` ${item.strengthValue}${item.strengthUnit??''}`:''}`).join(' + ')||'—'}</p><p>Barcode: {reference.barcodes.map(item=>item.value).join(' · ')||'—'} · EDA: {reference.regulatoryId||'—'}</p><p>آخر تحقق: {reference.lastVerifiedAt?formatDate(reference.lastVerifiedAt):'غير مسجل'}</p>{reference.quarantineReason&&<p className="warning">Conflict: {reference.quarantineReason}</p>}<div className="card-actions"><button onClick={()=>void onDetail(reference.id)}>المصدر / Provenance</button>{adoptedIds.has(reference.id)?<span className="adopted">موجود في كتالوج الشركة</span>:<button className="primary" disabled={!companyValid||reference.status!=='ACTIVE'} onClick={()=>void onAdopt(reference)}>اعتماد في الشركة</button>}</div>{status==='QUARANTINED'&&<div className="govern-inline"><input value={governNotes[reference.id]??''} onChange={event=>setGovernNotes(current=>({...current,[reference.id]:event.target.value}))} placeholder="سبب قرار الحوكمة"/><button onClick={()=>void govern(reference,'ACTIVE')}>حل التعارض وتفعيل</button><button onClick={()=>void govern(reference,'SUPERSEDED')}>Supersede</button><button onClick={()=>void govern(reference,'RETIRED')}>Retire</button></div>}</article>)}</div>
  <div className="pager"><button disabled={central.page<=1} onClick={()=>void onPage(central.page-1)}>السابق</button><span>{central.total} مرجع</span><button disabled={central.page*central.pageSize>=central.total} onClick={()=>void onPage(central.page+1)}>التالي</button></div>
  {detail&&<aside className="central-detail"><h3>{detail.reference.canonicalName}</h3><p><strong>المصدر:</strong> {detail.source.name} ({detail.source.sourceKey})</p><p><strong>Provenance:</strong> {detail.source.provenance}</p><p><strong>License:</strong> {detail.source.licenseNote||'غير مسجل'}</p><p><strong>Dataset:</strong> {detail.dataset?.datasetKey||'—'} · Published {detail.dataset?.publishedAt?formatDate(detail.dataset.publishedAt):'—'} · Ingested {detail.dataset?formatDate(detail.dataset.ingestedAt):'—'}</p>{detail.source.sourceUrl&&<a href={detail.source.sourceUrl} target="_blank" rel="noreferrer">فتح المصدر</a>}</aside>}
  <details className="admin-panel" onToggle={event=>{if(event.currentTarget.open)void onLoadAdmin();}}><summary>إدارة الكتالوج المركزي — Global فقط</summary>{adminError&&<p className="warning">{adminError}</p>}<form className="grid-form" onSubmit={createSource}><label>Source Key<input required value={sourceForm.sourceKey} onChange={event=>setSourceForm({...sourceForm,sourceKey:event.target.value})}/></label><label>اسم المصدر<input required value={sourceForm.name} onChange={event=>setSourceForm({...sourceForm,name:event.target.value})}/></label><label className="wide">Provenance<textarea required value={sourceForm.provenance} onChange={event=>setSourceForm({...sourceForm,provenance:event.target.value})}/></label><label>License<input value={sourceForm.licenseNote} onChange={event=>setSourceForm({...sourceForm,licenseNote:event.target.value})}/></label><label>URL<input value={sourceForm.sourceUrl} onChange={event=>setSourceForm({...sourceForm,sourceUrl:event.target.value})}/></label><button className="primary">حفظ المصدر</button></form><h3>المصادر</h3>{sources.map(source=><p key={source.id}>{source.name} · {source.active?'ACTIVE':'INACTIVE'} · {source.provenance}</p>)}<h3>Datasets</h3>{datasets.map(dataset=><p key={dataset.id}>{dataset.datasetKey} · {dataset.source.name} · {dataset.status} · {formatDate(dataset.ingestedAt)}</p>)}<h3>Import Sessions</h3>{sessions.map(session=><p key={session.id}>{session.id} · {session.datasetKey||session.sourceName} · {session.status} · {session.processedRows}/{session.totalRows??'?'} · Q {session.quarantinedRows}</p>)}</details>
 </section>;
}
