import { useState } from 'react';
import type { FormEvent } from 'react';
import type { Master, MasterGroups, MasterKind, Notice, RequestFn } from './types';
import { showError } from './types';

export function MastersView({masters,request,onReload,notice}:{masters:MasterGroups;request:RequestFn;onReload:()=>Promise<void>;notice:(notice:Notice)=>void}){const[kind,setKind]=useState<MasterKind>('category');const[name,setName]=useState('');const[parentId,setParentId]=useState('');const items=kind==='category'?masters.categories:kind==='tag'?masters.tags:kind==='manufacturer'?masters.manufacturers:kind==='ingredient'?masters.ingredients:kind==='dosage-form'?masters.dosageForms:masters.routes;
 async function create(event:FormEvent){event.preventDefault();try{await request(`/products/masters/${kind}`,{method:'POST',body:JSON.stringify({name:name.trim(),...(kind==='category'?{parentId:parentId||null}:{})})});setName('');setParentId('');await onReload();notice({kind:'success',text:'تمت إضافة القيمة المرجعية'});}catch(error){showError(error,notice);}}
 async function edit(item:Master){const next=window.prompt('الاسم',item.name);if(next===null||!next.trim())return;try{await request(`/products/masters/${kind}/${item.id}`,{method:'PATCH',body:JSON.stringify({name:next.trim(),active:item.active,parentId:kind==='category'?item.parentId??null:null})});await onReload();}catch(error){showError(error,notice);}}
 async function toggle(item:Master){try{await request(`/products/masters/${kind}/${item.id}`,{method:'PATCH',body:JSON.stringify({name:item.name,active:!item.active,parentId:kind==='category'?item.parentId??null:null})});await onReload();}catch(error){showError(error,notice);}}
 return <section className="masters"><div className="toolbar"><select value={kind} onChange={event=>setKind(event.target.value as MasterKind)}><option value="category">التصنيفات</option><option value="tag">Tags</option><option value="manufacturer">الشركات المصنعة</option><option value="ingredient">المواد الفعالة</option><option value="dosage-form">الأشكال الدوائية</option><option value="route">طرق الاستخدام</option></select></div><form className="inline-form" onSubmit={create}><input required value={name} onChange={event=>setName(event.target.value)} placeholder="اسم جديد"/>{kind==='category'&&<select value={parentId} onChange={event=>setParentId(event.target.value)}><option value="">بدون تصنيف أب</option>{masters.categories.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}<button className="primary">إضافة</button></form><div className="master-list">{items.map(item=><div key={item.id}><strong>{item.name}</strong><span>{item.active?'نشط':'غير نشط'}</span><div><button onClick={()=>void edit(item)}>تعديل</button><button onClick={()=>void toggle(item)}>{item.active?'تعطيل':'تفعيل'}</button></div></div>)}</div></section>;
}
