import { useEffect, useState } from 'react';
import type { CentralDrugReferenceView, ProductBarcodeView, ProductDetail, ProductStatus, ProductUnitView } from '../../contracts';
import type { AuditPage, Notice, RequestFn } from './types';
import { formatDate, showError } from './types';
import { Info } from './ui';

export function ProductProfile({product,onEdit,onStatus,request,refresh,baseUrl,accessToken,notice}:{product:ProductDetail;onEdit:()=>void;onStatus:(status:ProductStatus)=>Promise<void>;request:RequestFn;refresh:()=>Promise<void>;baseUrl:string;accessToken:string;notice:(notice:Notice)=>void}){
 const[compare,setCompare]=useState<{central:CentralDrugReferenceView;snapshot:unknown}|null>(null);const[sections,setSections]=useState<string[]>(['names']);
 async function loadCompare(){try{setCompare(await request(`/products/${product.id}/central-compare`));}catch(error){showError(error,notice);}}
 async function apply(){if(!sections.length)return;try{await request(`/products/${product.id}/central-apply`,{method:'POST',body:JSON.stringify({version:product.version,sections})});await refresh();setCompare(null);notice({kind:'success',text:'تم تطبيق الأقسام المركزية المحددة فقط'});}catch(error){showError(error,notice);}}
 return <div className="product-profile"><div className="panel-title"><div><h2>{product.displayName}</h2><span>{product.productCode}</span></div><button type="button" onClick={onEdit} disabled={product.status==='ARCHIVED'}>تعديل</button></div>
  {product.imageFileId&&<AuthenticatedImage fileId={product.imageFileId} baseUrl={baseUrl} accessToken={accessToken}/>}<div className="profile-grid"><Info label="النوع" value={product.productType}/><Info label="الحالة" value={product.status}/><Info label="العربي" value={product.arabicName}/><Info label="الإنجليزي" value={product.englishName}/><Info label="Trade" value={product.tradeName}/><Info label="الشركة" value={product.manufacturer?.name}/><Info label="التصنيف" value={product.category?.name}/><Info label="EDA" value={product.regulatoryId}/><Info label="ATC" value={product.atcCode}/><Info label="Prescription" value={product.prescriptionClass}/><Info label="Market" value={product.marketStatus}/><Info label="السعر المرجعي" value={product.referencePrice}/></div>
  <section className="profile-section"><h3>المواد الفعالة</h3>{product.ingredients.length?product.ingredients.map(item=><p key={item.id}>{item.ingredient.name} {item.strengthValue??''} {item.strengthUnit??''}</p>):<p>—</p>}</section>
  <section className="profile-section"><h3>Tags</h3><p>{product.tags.map(tag=>tag.name).join(' · ')||'—'}</p></section>
  <UnitManager product={product} request={request} refresh={refresh} notice={notice}/><BarcodeManager product={product} request={request} refresh={refresh} notice={notice}/>
  <div className="profile-actions">{product.status==='DRAFT'&&<button className="primary" onClick={()=>void onStatus('ACTIVE')}>تفعيل</button>}{product.status==='ACTIVE'&&<button onClick={()=>void onStatus('INACTIVE')}>إيقاف</button>}{product.status==='INACTIVE'&&<button className="primary" onClick={()=>void onStatus('ACTIVE')}>إعادة تفعيل</button>}{product.status!=='ARCHIVED'&&<button className="danger" onClick={()=>void onStatus('ARCHIVED')}>أرشفة</button>}{product.status==='ARCHIVED'&&<button onClick={()=>void onStatus('DRAFT')}>استعادة كمسودة</button>}<button onClick={()=>void navigator.clipboard.writeText(product.productCode)}>نسخ الكود</button>{product.primaryBarcode&&<button onClick={()=>void navigator.clipboard.writeText(product.primaryBarcode)}>نسخ الباركود</button>}</div>
  {product.centralReferenceId&&<section className="profile-section"><h3>المرجع المركزي</h3><p>ID: {product.centralReferenceId}</p><button onClick={()=>void loadCompare()}>مقارنة التحديثات</button>{compare&&<div className="compare-panel"><p>المرجع: <strong>{compare.central.canonicalName}</strong> · {compare.central.status}</p>{(['names','drug-profile','manufacturer','ingredients','packaging','barcodes','reference-price'] as const).map(section=><label className="check" key={section}><input type="checkbox" checked={sections.includes(section)} onChange={event=>setSections(event.target.checked?[...sections,section]:sections.filter(value=>value!==section))}/>{section}</label>)}<button className="primary" disabled={!sections.length} onClick={()=>void apply()}>تطبيق المحدد</button></div>}</section>}
  <AuditPanel productId={product.id} request={request}/>
 </div>;
}

function AuthenticatedImage({fileId,baseUrl,accessToken}:{fileId:string;baseUrl:string;accessToken:string}){const[url,setUrl]=useState('');useEffect(()=>{let active=true;let objectUrl='';void fetch(`${baseUrl}/files/${fileId}/download`,{headers:{Authorization:`Bearer ${accessToken}`}}).then(async response=>{if(!response.ok)throw new Error('image');objectUrl=URL.createObjectURL(await response.blob());if(active)setUrl(objectUrl);}).catch(()=>undefined);return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[fileId,baseUrl,accessToken]);return url?<img className="product-image" src={url} alt="صورة الصنف"/>:<div className="image-placeholder">صورة مرتبطة: {fileId}</div>}

function UnitManager({product,request,refresh,notice}:{product:ProductDetail;request:RequestFn;refresh:()=>Promise<void>;notice:(notice:Notice)=>void}){const[name,setName]=useState('');const[factor,setFactor]=useState('1');async function add(){if(!name.trim())return;try{await request(`/products/${product.id}/units`,{method:'POST',body:JSON.stringify({name:name.trim(),conversionFactor:factor,active:true})});setName('');setFactor('1');await refresh();}catch(error){showError(error,notice);}}async function patch(unit:ProductUnitView,change:Partial<ProductUnitView>){try{await request(`/products/${product.id}/units/${unit.id}`,{method:'PATCH',body:JSON.stringify({name:change.name??unit.name,shortLabel:change.shortLabel??unit.shortLabel,conversionFactor:change.conversionFactor??unit.conversionFactor,isBase:change.isBase??unit.isBase,defaultSale:change.defaultSale??unit.defaultSale,defaultPurchase:change.defaultPurchase??unit.defaultPurchase,active:change.active??unit.active,version:unit.version})});await refresh();}catch(error){showError(error,notice);}}async function deactivate(unit:ProductUnitView){try{await request(`/products/${product.id}/units/${unit.id}/deactivate`,{method:'POST',body:JSON.stringify({version:unit.version})});await refresh();}catch(error){showError(error,notice);}}return <section className="profile-section"><h3>الوحدات والتعبئة</h3>{product.units.map(unit=><div className="managed-row" key={unit.id}><span><strong>{unit.name}</strong> × {unit.conversionFactor} {unit.isBase?'· أساسية':''} {unit.defaultSale?'· بيع':''} {unit.defaultPurchase?'· شراء':''} {!unit.active?'· غير نشطة':''}</span>{unit.active&&<div><button onClick={()=>void patch(unit,{isBase:true,conversionFactor:'1'})}>اجعلها أساسية</button><button onClick={()=>void patch(unit,{defaultSale:true})}>افتراضي بيع</button><button onClick={()=>void patch(unit,{defaultPurchase:true})}>افتراضي شراء</button>{!unit.isBase&&<button onClick={()=>void deactivate(unit)}>تعطيل</button>}</div>}</div>)}<div className="inline-form"><input value={name} onChange={event=>setName(event.target.value)} placeholder="وحدة جديدة"/><input type="number" min="0.000001" step="any" value={factor} onChange={event=>setFactor(event.target.value)}/><button onClick={()=>void add()}>إضافة وحدة</button></div></section>}

function BarcodeManager({product,request,refresh,notice}:{product:ProductDetail;request:RequestFn;refresh:()=>Promise<void>;notice:(notice:Notice)=>void}){const[value,setValue]=useState('');const[unitId,setUnitId]=useState(product.units.find(unit=>unit.active)?.id??'');useEffect(()=>{if(!product.units.some(unit=>unit.id===unitId&&unit.active))setUnitId(product.units.find(unit=>unit.active)?.id??'');},[product.units,unitId]);async function add(){if(!value.trim()||!unitId)return;try{await request(`/products/${product.id}/barcodes`,{method:'POST',body:JSON.stringify({unitId,value:value.trim(),isPrimary:product.barcodes.every(item=>!item.active),active:true,source:'manual'})});setValue('');await refresh();}catch(error){showError(error,notice);}}async function patch(barcode:ProductBarcodeView,change:Partial<ProductBarcodeView>){try{await request(`/products/${product.id}/barcodes/${barcode.id}`,{method:'PATCH',body:JSON.stringify({unitId:change.unitId??barcode.unitId,value:change.value??barcode.value,symbology:change.symbology??barcode.symbology,isPrimary:change.isPrimary??barcode.isPrimary,active:change.active??barcode.active,source:change.source??barcode.source,version:barcode.version})});await refresh();}catch(error){showError(error,notice);}}async function deactivate(barcode:ProductBarcodeView){try{await request(`/products/${product.id}/barcodes/${barcode.id}/deactivate`,{method:'POST',body:JSON.stringify({version:barcode.version})});await refresh();}catch(error){showError(error,notice);}}return <section className="profile-section"><h3>الباركود</h3>{product.barcodes.map(barcode=><div className="managed-row" key={barcode.id}><span className="mono">{barcode.value} {barcode.isPrimary?'· أساسي':''} {!barcode.active?'· غير نشط':''}</span>{barcode.active&&<div>{!barcode.isPrimary&&<button onClick={()=>void patch(barcode,{isPrimary:true})}>اجعله أساسيًا</button>}<button onClick={()=>void navigator.clipboard.writeText(barcode.value)}>نسخ</button><button onClick={()=>void deactivate(barcode)}>تعطيل</button></div>}</div>)}<div className="inline-form"><input value={value} onChange={event=>setValue(event.target.value)} placeholder="باركود جديد"/><select value={unitId} onChange={event=>setUnitId(event.target.value)}>{product.units.filter(unit=>unit.active).map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select><button onClick={()=>void add()}>إضافة باركود</button></div></section>}

function AuditPanel({productId,request}:{productId:string;request:RequestFn}){const[history,setHistory]=useState<AuditPage|null>(null);const[open,setOpen]=useState(false);async function load(page=1){setHistory(await request(`/products/${productId}/audit?page=${page}&pageSize=20`));}useEffect(()=>{setHistory(null);setOpen(false);},[productId]);return <section className="profile-section audit-panel"><div className="section-title"><h3>سجل التدقيق</h3><button onClick={()=>{setOpen(!open);if(!open&&!history)void load();}}>{open?'إخفاء':'عرض السجل'}</button></div>{open&&history&&<>{history.items.map(record=><article key={record.id}><strong>{record.action}</strong><span>{formatDate(record.occurredAt)} · {record.actorId??'System'} {record.branchId?`· فرع ${record.branchId}`:''}</span><small>Request: {record.requestId??'—'}</small></article>)}<div className="pager"><button disabled={history.page<=1} onClick={()=>void load(history.page-1)}>السابق</button><span>{history.total} حدث</span><button disabled={history.page*history.pageSize>=history.total} onClick={()=>void load(history.page+1)}>التالي</button></div></>}</section>}
