import { useCallback, useEffect, useMemo, useState } from 'react';
import type { CentralDrugReferenceDetailView, CentralDrugReferenceView, CentralDrugSourceView, ProductDetail, ProductStatus, ProductSummary } from '../../contracts';
import { CatalogView } from './catalog';
import { CentralView } from './central';
import { ImportCenter } from './import-center';
import { MastersView } from './masters';
import type { CentralDataset, Filters, ImportSession, ListResponse, Master, MasterGroups, MasterKind, Notice, ProductForm, Tab, Tri } from './types';
import { errorMessage, idempotencyKey, initialFilters, newProductForm, nullable, showError, uuidPattern } from './types';

export interface ProductsWorkspaceProps{baseUrl:string;accessToken:string}
export function ProductsWorkspace({baseUrl,accessToken}:ProductsWorkspaceProps){
 const[companyId,setCompanyId]=useState(()=>localStorage.getItem('elhafez.products.company')??'');const[tab,setTab]=useState<Tab>('catalog');const[filters,setFilters]=useState<Filters>(initialFilters);const[list,setList]=useState<ListResponse>({items:[],page:1,pageSize:25,total:0});
 const[selected,setSelected]=useState<ProductDetail|null>(null);const[creating,setCreating]=useState(false);const[editing,setEditing]=useState(false);const[form,setForm]=useState<ProductForm>(newProductForm);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<Notice>(null);const[checked,setChecked]=useState<string[]>([]);const[filtersOpen,setFiltersOpen]=useState(false);
 const[categories,setCategories]=useState<Master[]>([]);const[tags,setTags]=useState<Master[]>([]);const[manufacturers,setManufacturers]=useState<Master[]>([]);const[ingredients,setIngredients]=useState<Master[]>([]);const[dosageForms,setDosageForms]=useState<Master[]>([]);const[routes,setRoutes]=useState<Master[]>([]);
 const[central,setCentral]=useState<{items:CentralDrugReferenceView[];page:number;pageSize:number;total:number}>({items:[],page:1,pageSize:25,total:0});const[centralSearch,setCentralSearch]=useState('');const[centralStatus,setCentralStatus]=useState('');const[centralManufacturer,setCentralManufacturer]=useState('');const[centralDosage,setCentralDosage]=useState('');const[centralStrength,setCentralStrength]=useState('');const[centralControlled,setCentralControlled]=useState<Tri>('');const[centralDetail,setCentralDetail]=useState<CentralDrugReferenceDetailView|null>(null);const[adoptedIds,setAdoptedIds]=useState<Set<string>>(new Set());
 const[sources,setSources]=useState<CentralDrugSourceView[]>([]);const[datasets,setDatasets]=useState<CentralDataset[]>([]);const[centralSessions,setCentralSessions]=useState<ImportSession[]>([]);const[adminError,setAdminError]=useState('');const companyValid=uuidPattern.test(companyId);
 const scopedHeaders=useMemo(()=>({Authorization:`Bearer ${accessToken}`,'x-company-id':companyId}),[accessToken,companyId]);
 const request=useCallback(async<T,>(path:string,init:RequestInit={}):Promise<T>=>{const response=await fetch(`${baseUrl}${path}`,{...init,headers:{...scopedHeaders,...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers??{})}});const payload=await response.json().catch(()=>null)as unknown;if(!response.ok)throw new Error(errorMessage(payload,response.status));return payload as T;},[baseUrl,scopedHeaders]);
 const globalRequest=useCallback(async<T,>(path:string,init:RequestInit={}):Promise<T>=>{const response=await fetch(`${baseUrl}${path}`,{...init,headers:{Authorization:`Bearer ${accessToken}`,...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers??{})}});const payload=await response.json().catch(()=>null)as unknown;if(!response.ok)throw new Error(errorMessage(payload,response.status));return payload as T;},[baseUrl,accessToken]);
 const masters:MasterGroups={categories,tags,manufacturers,ingredients,dosageForms,routes};
 const loadMasters=useCallback(async()=>{if(!companyValid)return;try{const kinds:MasterKind[]=['category','tag','manufacturer','ingredient','dosage-form','route'];const values=await Promise.all(kinds.map(kind=>request<Master[]>(`/products/masters/${kind}?includeInactive=true`)));setCategories(values[0]??[]);setTags(values[1]??[]);setManufacturers(values[2]??[]);setIngredients(values[3]??[]);setDosageForms(values[4]??[]);setRoutes(values[5]??[]);}catch(error){showError(error,setNotice);}},[companyValid,request]);
 const loadList=useCallback(async(page=1)=>{if(!companyValid)return;const params=new URLSearchParams({page:String(page),pageSize:'25',sortBy:filters.sortBy,sortDirection:filters.sortDirection});for(const[name,value]of Object.entries(filters)){if(name==='sortBy'||name==='sortDirection'||!value)continue;const isDate=['createdFrom','createdTo','updatedFrom','updatedTo'].includes(name);params.set(name,isDate?new Date(String(value)).toISOString():String(value));}try{setList(await request(`/products/query-v1?${params}`));}catch(error){showError(error,setNotice);}},[companyValid,filters,request]);
 const loadAdopted=useCallback(async()=>{if(!companyValid)return;try{const ids=new Set<string>();let page=1;for(;;){const result=await request<ListResponse>(`/products/query-v1?linkedCentral=true&page=${page}&pageSize=100&sortBy=UPDATED_AT&sortDirection=desc`);for(const product of result.items)if(product.centralReferenceId)ids.add(product.centralReferenceId);if(page*result.pageSize>=result.total)break;page+=1;}setAdoptedIds(ids);}catch{setAdoptedIds(new Set());}},[companyValid,request]);
 const loadCentral=useCallback(async(page=1)=>{const params=new URLSearchParams({page:String(page),pageSize:'25'});if(centralSearch.trim())params.set('search',centralSearch.trim());if(centralStatus)params.set('status',centralStatus);if(centralManufacturer.trim())params.set('manufacturer',centralManufacturer.trim());if(centralDosage.trim())params.set('dosageForm',centralDosage.trim());if(centralStrength.trim())params.set('strength',centralStrength.trim());if(centralControlled)params.set('controlled',centralControlled);try{setCentral(await request(`/products/central-v1?${params}`));}catch(error){showError(error,setNotice);}},[centralSearch,centralStatus,centralManufacturer,centralDosage,centralStrength,centralControlled,request]);
 const loadSources=useCallback(async()=>{try{setSources(await request('/products/central/sources'));}catch(error){showError(error,setNotice);}},[request]);
 const loadAdmin=useCallback(async()=>{setAdminError('');try{const[data,history]=await Promise.all([globalRequest<CentralDataset[]>('/products/central-admin/datasets?limit=50'),globalRequest<ImportSession[]>('/products/central-admin/import-sessions?limit=50')]);setDatasets(data);setCentralSessions(history);}catch(error){setAdminError(error instanceof Error?error.message:'الإدارة المركزية غير متاحة بهذه الصلاحية');}},[globalRequest]);
 useEffect(()=>{if(companyValid){localStorage.setItem('elhafez.products.company',companyId);void loadMasters();void loadAdopted();}},[companyId,companyValid,loadMasters,loadAdopted]);useEffect(()=>{const timer=setTimeout(()=>void loadList(1),180);return()=>clearTimeout(timer);},[loadList]);useEffect(()=>{if(tab!=='central')return;const timer=setTimeout(()=>void loadCentral(1),180);void loadSources();void loadAdopted();return()=>clearTimeout(timer);},[tab,loadCentral,loadSources,loadAdopted]);
 async function openProduct(id:string){try{setSelected(await request(`/products/${id}`));setCreating(false);setEditing(false);}catch(error){showError(error,setNotice);}}
 function startCreate(){setSelected(null);setCreating(true);setEditing(false);setForm(newProductForm());}
 function startEdit(product:ProductDetail){if(product.status==='ARCHIVED')return setNotice({kind:'info',text:'استعد الصنف من الأرشيف قبل تعديله'});setCreating(false);setEditing(true);setForm(formFromProduct(product));}
 async function saveProduct(mode:'draft'|'activate'|'add-another'){if(!companyValid)return setNotice({kind:'error',text:'أدخل Company ID صالح أولًا'});setBusy(true);try{const body=productPayload(form,!editing);const duplicates=await request<ProductSummary[]>('/products/duplicates',{method:'POST',body:JSON.stringify(body)});if(!editing&&duplicates.length&&!window.confirm(`يوجد ${duplicates.length} صنف مشابه محتمل. هل تريد الاستمرار؟`))return;if(editing&&selected){let product=await request<ProductDetail>(`/products/${selected.id}`,{method:'PATCH',body:JSON.stringify({...body,version:selected.version})});if(mode==='activate'&&product.status!=='ACTIVE')product=await request(`/products/${product.id}/status`,{method:'PATCH',body:JSON.stringify({status:'ACTIVE',version:product.version})});setSelected(product);setEditing(false);setNotice({kind:'success',text:mode==='activate'?'تم الحفظ والتفعيل':'تم حفظ التعديلات'});}else{const result=await request<{product:ProductDetail;warnings:ProductSummary[]}>(`/products`,{method:'POST',headers:{'idempotency-key':idempotencyKey('product')},body:JSON.stringify({...body,activate:mode==='activate'})});setNotice({kind:'success',text:result.warnings.length?`تم الحفظ مع ${result.warnings.length} تشابه محتمل`:(mode==='activate'?'تم الحفظ والتفعيل':'تم حفظ المسودة')});if(mode==='add-another'){setForm(newProductForm());setCreating(true);setSelected(null);}else{setSelected(result.product);setCreating(false);}}await loadList(1);await loadAdopted();}catch(error){showError(error,setNotice);}finally{setBusy(false);}}
 async function statusChange(status:ProductStatus){if(!selected)return;setBusy(true);try{const product=await request<ProductDetail>(`/products/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status,version:selected.version})});setSelected(product);await loadList(list.page);}catch(error){showError(error,setNotice);}finally{setBusy(false);}}
 async function uploadImage(file:File){if(!file.type.startsWith('image/'))return setNotice({kind:'error',text:'اختر ملف صورة فقط'});setBusy(true);try{const base64=await fileBase64(file);const saved=await request<{id:string}>('/files',{method:'POST',body:JSON.stringify({originalName:file.name,mimeType:file.type,base64,companyId})});setForm(current=>({...current,imageFileId:saved.id}));setNotice({kind:'success',text:'تم رفع الصورة؛ احفظ الصنف لتثبيت المرجع'});}catch(error){showError(error,setNotice);}finally{setBusy(false);}}
 async function adopt(reference:CentralDrugReferenceView){if(!companyValid)return;setBusy(true);try{const result=await request<{product:ProductDetail;warnings?:ProductSummary[]}>(`/products/central/${reference.id}/adopt`,{method:'POST',headers:{'idempotency-key':idempotencyKey('adopt')}});setSelected(result.product);setTab('catalog');await loadList(1);await loadAdopted();setNotice({kind:'success',text:result.warnings?.length?`تم الربط مع ${result.warnings.length} تشابه محتمل`:'تم اعتماد المرجع في كتالوج الشركة'});}catch(error){showError(error,setNotice);}finally{setBusy(false);}}
 async function openCentralDetail(id:string){try{setCentralDetail(await request(`/products/central-v1/${id}`));}catch(error){showError(error,setNotice);}}
 return <div className="products-workspace products-v1" dir="rtl"><header className="products-header"><div><h1>الأصناف والأدوية</h1><p>كتالوج الشركة + الكتالوج الدوائي المصري المرجعي</p></div><label className="company-scope">Company ID<input value={companyId} onChange={event=>setCompanyId(event.target.value)} placeholder="UUID"/><span className={companyValid?'valid':'invalid'}>{companyValid?'نطاق صالح':'أدخل نطاق الشركة'}</span></label></header>{notice&&<div className={`products-notice ${notice.kind}`}>{notice.text}<button type="button" onClick={()=>setNotice(null)}>×</button></div>}<nav className="products-tabs"><button className={tab==='catalog'?'active':''} onClick={()=>setTab('catalog')}>كتالوج الشركة</button><button className={tab==='central'?'active':''} onClick={()=>setTab('central')}>الكتالوج المصري</button><button className={tab==='masters'?'active':''} onClick={()=>setTab('masters')}>البيانات المرجعية</button><button className={tab==='import'?'active':''} onClick={()=>setTab('import')}>استيراد / تصدير</button></nav>
 {tab==='catalog'&&<CatalogView companyValid={companyValid} list={list} filters={filters} setFilters={setFilters} filtersOpen={filtersOpen} setFiltersOpen={setFiltersOpen} masters={masters} selected={selected} checked={checked} setChecked={setChecked} onPage={loadList} onOpen={openProduct} onCreate={startCreate} creating={creating} editing={editing} form={form} setForm={setForm} busy={busy} onEdit={startEdit} onSave={saveProduct} onCancel={()=>{setCreating(false);setEditing(false);}} onStatus={statusChange} onImage={uploadImage} request={request} baseUrl={baseUrl} accessToken={accessToken} refreshSelected={async()=>{if(selected)await openProduct(selected.id);}} notice={setNotice}/>} 
 {tab==='central'&&<CentralView companyValid={companyValid} central={central} search={centralSearch} setSearch={setCentralSearch} status={centralStatus} setStatus={setCentralStatus} manufacturer={centralManufacturer} setManufacturer={setCentralManufacturer} dosage={centralDosage} setDosage={setCentralDosage} strength={centralStrength} setStrength={setCentralStrength} controlled={centralControlled} setControlled={setCentralControlled} onPage={loadCentral} onAdopt={adopt} adoptedIds={adoptedIds} detail={centralDetail} onDetail={openCentralDetail} sources={sources} datasets={datasets} sessions={centralSessions} adminError={adminError} onLoadAdmin={loadAdmin} globalRequest={globalRequest} onSources={loadSources} notice={setNotice}/>} 
 {tab==='masters'&&<MastersView masters={masters} request={request} onReload={loadMasters} notice={setNotice}/>} 
 {tab==='import'&&<ImportCenter companyValid={companyValid} request={request} globalRequest={globalRequest} sources={sources} onLoadSources={loadSources} notice={setNotice}/>}</div>;
}

function productPayload(form:ProductForm,includeChildren:boolean){const common={productType:form.productType,displayName:form.displayName,arabicName:nullable(form.arabicName),englishName:nullable(form.englishName),tradeName:nullable(form.tradeName),description:nullable(form.description),notes:nullable(form.notes),categoryId:nullable(form.categoryId),tagIds:form.tagIds,manufacturerId:nullable(form.manufacturerId),countryOfOrigin:nullable(form.countryOfOrigin),dosageFormId:form.productType==='DRUG'?nullable(form.dosageFormId):null,routeId:form.productType==='DRUG'?nullable(form.routeId):null,regulatoryId:form.productType==='DRUG'?nullable(form.regulatoryId):null,atcCode:form.productType==='DRUG'?nullable(form.atcCode):null,prescriptionClass:form.productType==='DRUG'?nullable(form.prescriptionClass):null,controlled:form.productType==='DRUG'&&form.controlled,coldChain:form.coldChain,storageNotes:nullable(form.storageNotes),marketStatus:form.marketStatus,referencePrice:nullable(form.referencePrice),referencePriceSource:nullable(form.referencePriceSource),referencePriceVerifiedAt:form.referencePriceVerifiedAt?new Date(form.referencePriceVerifiedAt).toISOString():null,imageFileId:nullable(form.imageFileId),ingredients:form.productType==='DRUG'?form.ingredients.filter(item=>item.ingredientId).map((item,index)=>({ingredientId:item.ingredientId,strengthValue:nullable(item.strengthValue),strengthUnit:nullable(item.strengthUnit),sortOrder:index})):[]};if(!includeChildren)return common;return{...common,units:form.units.map(unit=>({...unit,shortLabel:nullable(unit.shortLabel)})),barcodes:form.barcodes.filter(barcode=>barcode.value.trim()).map(barcode=>({value:barcode.value.trim(),unitRef:`u${Math.max(0,Math.min(barcode.unitIndex,form.units.length-1))}`,symbology:nullable(barcode.symbology),isPrimary:barcode.isPrimary,active:barcode.active,source:nullable(barcode.source)}))};}
function formFromProduct(product:ProductDetail):ProductForm{return{productType:product.productType,displayName:product.displayName,arabicName:product.arabicName??'',englishName:product.englishName??'',tradeName:product.tradeName??'',description:product.description??'',notes:product.notes??'',categoryId:product.category?.id??'',tagIds:product.tags.map(tag=>tag.id),manufacturerId:product.manufacturer?.id??'',countryOfOrigin:product.countryOfOrigin??'',dosageFormId:product.dosageForm?.id??'',routeId:product.route?.id??'',regulatoryId:product.regulatoryId??'',atcCode:product.atcCode??'',prescriptionClass:product.prescriptionClass??'',controlled:product.controlled,coldChain:product.coldChain,storageNotes:product.storageNotes??'',marketStatus:product.marketStatus,referencePrice:product.referencePrice??'',referencePriceSource:product.referencePriceSource??'',referencePriceVerifiedAt:product.referencePriceVerifiedAt?.slice(0,16)??'',imageFileId:product.imageFileId??'',ingredients:product.ingredients.length?product.ingredients.map(item=>({ingredientId:item.ingredient.id,strengthValue:item.strengthValue??'',strengthUnit:item.strengthUnit??''})):[{ingredientId:'',strengthValue:'',strengthUnit:''}],units:product.units.map(unit=>({name:unit.name,shortLabel:unit.shortLabel??'',conversionFactor:unit.conversionFactor,isBase:unit.isBase,defaultSale:unit.defaultSale,defaultPurchase:unit.defaultPurchase,active:unit.active})),barcodes:product.barcodes.map(barcode=>({value:barcode.value,symbology:barcode.symbology??'',unitIndex:Math.max(0,product.units.findIndex(unit=>unit.id===barcode.unitId)),isPrimary:barcode.isPrimary,active:barcode.active,source:barcode.source??''}))};}
async function fileBase64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(binary);}
