import type { ProductMarketStatus, ProductStatus, ProductType } from '../../contracts';

export type ProductDomainErrorCode = 'INVALID_NAME'|'INVALID_TEXT'|'INVALID_STATUS_TRANSITION'|'PRODUCT_ARCHIVED'|'INVALID_UNIT'|'INVALID_BARCODE'|'INVALID_DRUG_PROFILE'|'INVALID_PRICE'|'INVALID_IMPORT';
export class ProductDomainError extends Error { constructor(public readonly code:ProductDomainErrorCode,message:string){super(message);this.name='ProductDomainError';} }

export interface ProductIngredientDraft { ingredientId:string; strengthValue?:string|number|null; strengthUnit?:string|null; sortOrder?:number; }
export interface ProductUnitDraft { name:string; shortLabel?:string|null; conversionFactor:string|number; isBase?:boolean; defaultSale?:boolean; defaultPurchase?:boolean; active?:boolean; }
export interface ProductBarcodeDraft { value:string; unitRef?:string|null; symbology?:string|null; isPrimary?:boolean; active?:boolean; source?:string|null; }
export interface ProductDraftInput {
  productType:ProductType; displayName:string; arabicName?:string|null; englishName?:string|null; tradeName?:string|null; description?:string|null; notes?:string|null;
  categoryId?:string|null; tagIds?:string[]; manufacturerId?:string|null; countryOfOrigin?:string|null; dosageFormId?:string|null; routeId?:string|null;
  regulatoryId?:string|null; atcCode?:string|null; prescriptionClass?:string|null; controlled?:boolean; coldChain?:boolean; storageNotes?:string|null;
  marketStatus?:ProductMarketStatus; referencePrice?:string|number|null; referencePriceSource?:string|null; referencePriceVerifiedAt?:string|Date|null; imageFileId?:string|null;
  ingredients?:ProductIngredientDraft[]; units?:ProductUnitDraft[]; barcodes?:ProductBarcodeDraft[];
}
export interface NormalizedProductDraft extends Omit<ProductDraftInput,'displayName'|'arabicName'|'englishName'|'tradeName'|'description'|'notes'|'countryOfOrigin'|'regulatoryId'|'atcCode'|'prescriptionClass'|'storageNotes'|'referencePrice'|'referencePriceSource'|'referencePriceVerifiedAt'|'ingredients'|'units'|'barcodes'|'tagIds'> {
  displayName:string; normalizedName:string; arabicName:string|null; normalizedArabicName:string|null; englishName:string|null; normalizedEnglishName:string|null;
  tradeName:string|null; normalizedTradeName:string|null; description:string|null; notes:string|null; categoryId:string|null; tagIds:string[]; manufacturerId:string|null;
  countryOfOrigin:string|null; dosageFormId:string|null; routeId:string|null; regulatoryId:string|null; atcCode:string|null; prescriptionClass:string|null;
  controlled:boolean; coldChain:boolean; storageNotes:string|null; marketStatus:ProductMarketStatus; referencePrice:string|null; referencePriceSource:string|null;
  referencePriceVerifiedAt:Date|null; imageFileId:string|null; ingredients:NormalizedProductIngredientDraft[]; units:NormalizedProductUnitDraft[]; barcodes:NormalizedProductBarcodeDraft[];
}
export interface NormalizedProductIngredientDraft { ingredientId:string; strengthValue:string|null; strengthUnit:string|null; sortOrder:number; }
export interface NormalizedProductUnitDraft { clientRef:string; name:string; shortLabel:string|null; conversionFactor:string; isBase:boolean; defaultSale:boolean; defaultPurchase:boolean; active:boolean; }
export interface NormalizedProductBarcodeDraft { value:string; unitRef:string|null; symbology:string|null; isPrimary:boolean; active:boolean; source:string|null; }

function controls(value:string){for(const char of value){const n=char.charCodeAt(0);if(n<32||n===127)return true;}return false;}
export function cleanText(value:string|null|undefined,max:number):string|null{if(value==null)return null;const clean=value.trim().replace(/\s+/g,' ');if(!clean)return null;if(clean.length>max||controls(clean))throw new ProductDomainError('INVALID_TEXT','Text value is invalid or too long');return clean;}
export function normalizeSearchText(value:string):string{return value.normalize('NFKC').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US');}
export function normalizeProductName(value:string):string{const clean=cleanText(value,200);if(!clean)throw new ProductDomainError('INVALID_NAME','Product display name is required');return clean;}
export function normalizeStrongCode(value:string|null|undefined,max=100):string|null{if(value==null||!value.trim())return null;const clean=value.trim().replace(/\s+/g,'').toLocaleUpperCase('en-US');if(clean.length>max||controls(clean))throw new ProductDomainError('INVALID_TEXT','Identifier is invalid');return clean;}
export function normalizeBarcode(value:string):string{const clean=value.trim().replace(/[\s-]/g,'');if(!clean||clean.length>64||!/^[0-9A-Za-z._/:+]+$/.test(clean))throw new ProductDomainError('INVALID_BARCODE','Barcode is invalid');return clean;}
function decimal(value:string|number|null|undefined,allowNull=true):string|null{if(value==null||value===''){if(allowNull)return null;throw new ProductDomainError('INVALID_UNIT','Numeric value is required');}const raw=String(value).trim();if(!/^\d+(?:\.\d{1,6})?$/.test(raw))throw new ProductDomainError('INVALID_UNIT','Numeric value must be positive decimal');const n=Number(raw);if(!Number.isFinite(n)||n<0)throw new ProductDomainError('INVALID_UNIT','Numeric value must be non-negative');return raw;}
export function normalizePrice(value:string|number|null|undefined):string|null{const v=decimal(value);if(v!==null&&Number(v)<0)throw new ProductDomainError('INVALID_PRICE','Reference price cannot be negative');return v;}
export function normalizeUnitDraft(input:ProductUnitDraft,index=0):NormalizedProductUnitDraft{const name=cleanText(input.name,120);if(!name)throw new ProductDomainError('INVALID_UNIT','Unit name is required');const factor=decimal(input.conversionFactor,false)!;if(Number(factor)<=0)throw new ProductDomainError('INVALID_UNIT','Conversion factor must be greater than zero');const isBase=input.isBase??false;if(isBase&&Number(factor)!==1)throw new ProductDomainError('INVALID_UNIT','Base unit conversion factor must equal 1');return{clientRef:`u${index}`,name,shortLabel:cleanText(input.shortLabel,40),conversionFactor:factor,isBase,defaultSale:input.defaultSale??false,defaultPurchase:input.defaultPurchase??false,active:input.active??true};}
export function normalizeBarcodeDraft(input:ProductBarcodeDraft):NormalizedProductBarcodeDraft{return{value:normalizeBarcode(input.value),unitRef:input.unitRef?.trim()||null,symbology:cleanText(input.symbology,30)?.toLocaleUpperCase('en-US')??null,isPrimary:input.isPrimary??false,active:input.active??true,source:cleanText(input.source,180)};}
export function normalizeIngredientDraft(input:ProductIngredientDraft,index=0):NormalizedProductIngredientDraft{const ingredientId=input.ingredientId.trim();if(!ingredientId)throw new ProductDomainError('INVALID_DRUG_PROFILE','Ingredient is required');const strength=input.strengthValue==null||input.strengthValue===''?null:decimal(input.strengthValue);return{ingredientId,strengthValue:strength,strengthUnit:cleanText(input.strengthUnit,40),sortOrder:input.sortOrder??index};}
export function normalizeProductDraft(input:ProductDraftInput):NormalizedProductDraft{
 const displayName=normalizeProductName(input.displayName);const arabicName=cleanText(input.arabicName,200);const englishName=cleanText(input.englishName,200);const tradeName=cleanText(input.tradeName,200);
 const units=(input.units??[]).map(normalizeUnitDraft);const activeBases=units.filter(x=>x.active&&x.isBase);if(activeBases.length>1)throw new ProductDomainError('INVALID_UNIT','At most one active base unit is allowed while drafting');
 const barcodes=(input.barcodes??[]).map(normalizeBarcodeDraft);if(new Set(barcodes.filter(x=>x.active).map(x=>x.value)).size!==barcodes.filter(x=>x.active).length)throw new ProductDomainError('INVALID_BARCODE','Duplicate active barcode in product');
 if(barcodes.filter(x=>x.active&&x.isPrimary).length>1)throw new ProductDomainError('INVALID_BARCODE','At most one primary active barcode is allowed');
 const ingredients=(input.ingredients??[]).map(normalizeIngredientDraft);if(input.productType==='NON_DRUG'&&ingredients.length)throw new ProductDomainError('INVALID_DRUG_PROFILE','Non-drug product cannot contain drug ingredients');
 return{productType:input.productType,displayName,normalizedName:normalizeSearchText(displayName),arabicName,normalizedArabicName:arabicName?normalizeSearchText(arabicName):null,englishName,normalizedEnglishName:englishName?normalizeSearchText(englishName):null,tradeName,normalizedTradeName:tradeName?normalizeSearchText(tradeName):null,description:cleanText(input.description,4000),notes:cleanText(input.notes,4000),categoryId:input.categoryId?.trim()||null,tagIds:[...new Set(input.tagIds??[])],manufacturerId:input.manufacturerId?.trim()||null,countryOfOrigin:cleanText(input.countryOfOrigin,120),dosageFormId:input.dosageFormId?.trim()||null,routeId:input.routeId?.trim()||null,regulatoryId:normalizeStrongCode(input.regulatoryId,120),atcCode:normalizeStrongCode(input.atcCode,40),prescriptionClass:cleanText(input.prescriptionClass,40)?.toLocaleUpperCase('en-US')??null,controlled:input.controlled??false,coldChain:input.coldChain??false,storageNotes:cleanText(input.storageNotes,1000),marketStatus:input.marketStatus??'UNKNOWN',referencePrice:normalizePrice(input.referencePrice),referencePriceSource:cleanText(input.referencePriceSource,300),referencePriceVerifiedAt:input.referencePriceVerifiedAt?new Date(input.referencePriceVerifiedAt):null,imageFileId:input.imageFileId?.trim()||null,ingredients,units,barcodes};
}
export function assertActivationReady(draft:NormalizedProductDraft):void{if(draft.units.filter(x=>x.active&&x.isBase).length!==1)throw new ProductDomainError('INVALID_UNIT','Active product requires exactly one active base unit');if(draft.productType==='DRUG'&&draft.ingredients.length===0)throw new ProductDomainError('INVALID_DRUG_PROFILE','Active drug requires at least one active ingredient');}
const transitions:Record<ProductStatus,readonly ProductStatus[]>={DRAFT:['ACTIVE','ARCHIVED'],ACTIVE:['INACTIVE','ARCHIVED'],INACTIVE:['ACTIVE','ARCHIVED'],ARCHIVED:['DRAFT','ACTIVE']};
export function assertStatusTransition(from:ProductStatus,to:ProductStatus):void{if(!transitions[from].includes(to))throw new ProductDomainError('INVALID_STATUS_TRANSITION',`Status transition ${from} -> ${to} is not allowed`);}
export function assertProductEditable(status:ProductStatus):void{if(status==='ARCHIVED')throw new ProductDomainError('PRODUCT_ARCHIVED','Archived product must be restored before modification');}
