import { randomUUID } from 'node:crypto';
import { Inject, Injectable } from '@nestjs/common';
import { ConflictError, InvariantViolationError, NotFoundError, ValidationError } from '@elhafez/errors';
import { EventBus } from '@elhafez/events';
import { StructuredLogger } from '@elhafez/logging';
import type { AuditRequestedEvent } from '@elhafez/platform-contracts';
import type { BarcodeResolution, ProductChangedEvent, ProductDetail, ProductReader, ProductStatus, ProductSummary } from '../../contracts';
import {
 assertActivationReady, assertProductEditable, assertStatusTransition, cleanText, normalizeBarcode, normalizeBarcodeDraft, normalizeProductDraft, normalizeSearchText, normalizeUnitDraft, ProductDomainError,
 type ProductBarcodeDraft, type ProductDraftInput, type ProductUnitDraft,
} from '../domain/product';
import {
 PRODUCTS_REPOSITORY, ProductClassificationError, ProductConcurrentUpdateError, ProductPersistenceConflictError,
 type CentralApplySection, type CentralImportContext, type CentralImportRow, type CentralSearchQuery, type CentralSourceInput, type CompanyImportRow,
 type ImportChunkResult, type MasterKind, type ProductCreateRecord, type ProductListQuery, type ProductsRepository,
} from './products.repository';

export interface ProductMutationContext { companyId:string; actorId:string; branchId?:string; requestId?:string; }
export interface GlobalMutationContext { actorId:string; requestId?:string; }
export interface CreateProductInput extends ProductDraftInput { activate?:boolean; }
export type UpdateProductInput=Partial<Omit<ProductDraftInput,'units'|'barcodes'>> & {version:number};
export type UpdateUnitInput=Partial<ProductUnitDraft>&{version:number};
export type UpdateBarcodeInput=Partial<ProductBarcodeDraft>&{version:number;unitId?:string};
export interface StartCompanyImportInput { mode:'CREATE_ONLY'|'UPSERT_PRODUCT_CODE'|'UPSERT_BARCODE'; mapping?:unknown; totalRows?:number|null; sourceName?:string|null; }
export interface StartCentralImportInput { sourceId:string; datasetKey:string; publishedAt?:Date|null; mapping?:unknown; totalRows?:number|null; sourceName?:string|null; }

function hasOwn(value:object,key:PropertyKey):boolean{return Object.prototype.hasOwnProperty.call(value,key);}
function csvCell(value:unknown):string{const text=value==null?'':String(value);return /[",\n\r]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}

@Injectable()
export class ProductsService implements ProductReader {
 constructor(@Inject(PRODUCTS_REPOSITORY) private readonly repository:ProductsRepository,private readonly events:EventBus,private readonly logger:StructuredLogger){}

 list(query:ProductListQuery){return this.repository.list(query);}
 async get(companyId:string,productId:string):Promise<ProductDetail>{const p=await this.repository.get(companyId,productId);if(!p)throw new NotFoundError('Product not found in authorized company');return p;}
 async getProductSummary(companyId:string,productId:string):Promise<ProductSummary|null>{const p=await this.repository.get(companyId,productId);return p?this.summary(p):null;}
 async isProductAvailable(companyId:string,productId:string):Promise<boolean>{return (await this.repository.get(companyId,productId))?.status==='ACTIVE';}
 async resolveBarcode(companyId:string,barcode:string):Promise<BarcodeResolution|null>{return this.repository.resolveBarcode(companyId,this.domain(()=>normalizeBarcode(barcode)));}
 async findLikelyDuplicates(companyId:string,input:ProductDraftInput){const d=this.domain(()=>normalizeProductDraft(input));return this.repository.findLikelyDuplicates(companyId,{normalizedName:d.normalizedName,normalizedArabicName:d.normalizedArabicName,normalizedEnglishName:d.normalizedEnglishName,normalizedTradeName:d.normalizedTradeName,manufacturerId:d.manufacturerId,regulatoryId:d.regulatoryId,barcodes:d.barcodes.filter(x=>x.active).map(x=>x.value),ingredientIds:d.ingredients.map(x=>x.ingredientId)});}

 async create(input:CreateProductInput,idempotencyKey:string,context:ProductMutationContext){
  this.idempotency(idempotencyKey);const replay=await this.repository.findByCreateRequestKey(context.companyId,idempotencyKey);if(replay)return{product:replay,warnings:[],replayed:true};
  const draft=this.domain(()=>normalizeProductDraft(input));if(input.activate)this.domain(()=>assertActivationReady(draft));const warnings=await this.repository.findLikelyDuplicates(context.companyId,{normalizedName:draft.normalizedName,normalizedArabicName:draft.normalizedArabicName,normalizedEnglishName:draft.normalizedEnglishName,normalizedTradeName:draft.normalizedTradeName,manufacturerId:draft.manufacturerId,regulatoryId:draft.regulatoryId,barcodes:draft.barcodes.filter(x=>x.active).map(x=>x.value),ingredientIds:draft.ingredients.map(x=>x.ingredientId)});
  const id=randomUUID();const record:ProductCreateRecord={id,companyId:context.companyId,productCode:`PRD-${id.replaceAll('-','').slice(0,10).toUpperCase()}`,createRequestKey:idempotencyKey,draft,status:input.activate?'ACTIVE':'DRAFT'};
  const product=await this.persistence(()=>this.repository.create(record));await this.audit('product.created',context,product.id,undefined,product,{idempotencyKey});await this.publish('products.product.created',product);this.logger.log({action:'products.create',companyId:context.companyId,productId:product.id},'ProductsService');return{product,warnings,replayed:false};
 }

 async update(productId:string,input:UpdateProductInput,context:ProductMutationContext){
  const before=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(before.status));
  const merged:ProductDraftInput={productType:input.productType??before.productType,displayName:input.displayName??before.displayName,arabicName:hasOwn(input,'arabicName')?input.arabicName:before.arabicName,englishName:hasOwn(input,'englishName')?input.englishName:before.englishName,tradeName:hasOwn(input,'tradeName')?input.tradeName:before.tradeName,description:hasOwn(input,'description')?input.description:before.description,notes:hasOwn(input,'notes')?input.notes:before.notes,categoryId:hasOwn(input,'categoryId')?input.categoryId:before.category?.id??null,tagIds:hasOwn(input,'tagIds')?input.tagIds:before.tags.map(x=>x.id),manufacturerId:hasOwn(input,'manufacturerId')?input.manufacturerId:before.manufacturer?.id??null,countryOfOrigin:hasOwn(input,'countryOfOrigin')?input.countryOfOrigin:before.countryOfOrigin,dosageFormId:hasOwn(input,'dosageFormId')?input.dosageFormId:before.dosageForm?.id??null,routeId:hasOwn(input,'routeId')?input.routeId:before.route?.id??null,regulatoryId:hasOwn(input,'regulatoryId')?input.regulatoryId:before.regulatoryId,atcCode:hasOwn(input,'atcCode')?input.atcCode:before.atcCode,prescriptionClass:hasOwn(input,'prescriptionClass')?input.prescriptionClass:before.prescriptionClass,controlled:input.controlled??before.controlled,coldChain:input.coldChain??before.coldChain,storageNotes:hasOwn(input,'storageNotes')?input.storageNotes:before.storageNotes,marketStatus:input.marketStatus??before.marketStatus,referencePrice:hasOwn(input,'referencePrice')?input.referencePrice:before.referencePrice,referencePriceSource:hasOwn(input,'referencePriceSource')?input.referencePriceSource:before.referencePriceSource,referencePriceVerifiedAt:hasOwn(input,'referencePriceVerifiedAt')?input.referencePriceVerifiedAt:before.referencePriceVerifiedAt,imageFileId:hasOwn(input,'imageFileId')?input.imageFileId:before.imageFileId,ingredients:hasOwn(input,'ingredients')?input.ingredients:before.ingredients.map(x=>({ingredientId:x.ingredient.id,strengthValue:x.strengthValue,strengthUnit:x.strengthUnit,sortOrder:x.sortOrder}))};
  const draft=this.domain(()=>normalizeProductDraft(merged));if(before.status==='ACTIVE')this.activationWithExistingUnits(draft,before);
  const product=await this.persistence(()=>this.repository.update({companyId:context.companyId,productId,expectedVersion:input.version,draft}));await this.audit('product.updated',context,productId,before,product);await this.publish('products.product.updated',product);return product;
 }

 async changeStatus(productId:string,status:ProductStatus,version:number,context:ProductMutationContext){const before=await this.get(context.companyId,productId);this.domain(()=>assertStatusTransition(before.status,status));if(status==='ACTIVE'){const d=this.domain(()=>normalizeProductDraft(this.toDraft(before)));this.activationWithExistingUnits(d,before);}const product=await this.persistence(()=>this.repository.changeStatus(context.companyId,productId,version,status));await this.audit('product.status-changed',context,productId,{status:before.status},{status:product.status});await this.publish('products.product.status-changed',product);return product;}

 async addUnit(productId:string,input:ProductUnitDraft,context:ProductMutationContext){const p=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(p.status));const unit=await this.persistence(()=>this.repository.addUnit(context.companyId,productId,this.domain(()=>normalizeUnitDraft(input))));await this.audit('product.unit-created',context,productId,undefined,unit,{unitId:unit.id});await this.publish('products.product.unit-changed',await this.get(context.companyId,productId));return unit;}
 async updateUnit(productId:string,unitId:string,input:UpdateUnitInput,context:ProductMutationContext){const p=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(p.status));const before=p.units.find(x=>x.id===unitId);if(!before)throw new NotFoundError('Product unit not found');const normalized=this.domain(()=>normalizeUnitDraft({name:input.name??before.name,shortLabel:hasOwn(input,'shortLabel')?input.shortLabel:before.shortLabel,conversionFactor:input.conversionFactor??before.conversionFactor,isBase:input.isBase??before.isBase,defaultSale:input.defaultSale??before.defaultSale,defaultPurchase:input.defaultPurchase??before.defaultPurchase,active:input.active??before.active}));const unit=await this.persistence(()=>this.repository.updateUnit(context.companyId,productId,unitId,{...normalized,expectedVersion:input.version}));await this.audit('product.unit-updated',context,productId,before,unit,{unitId});await this.publish('products.product.unit-changed',await this.get(context.companyId,productId));return unit;}
 async deactivateUnit(productId:string,unitId:string,version:number,context:ProductMutationContext){const p=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(p.status));const before=p.units.find(x=>x.id===unitId&&x.active);if(!before)throw new NotFoundError('Active product unit not found');if(before.isBase)throw new InvariantViolationError('Base unit cannot be deactivated before another base unit is selected');const unit=await this.persistence(()=>this.repository.deactivateUnit(context.companyId,productId,unitId,version));await this.audit('product.unit-deactivated',context,productId,before,unit,{unitId});await this.publish('products.product.unit-changed',await this.get(context.companyId,productId));return unit;}

 async addBarcode(productId:string,unitId:string,input:ProductBarcodeDraft,context:ProductMutationContext){const p=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(p.status));if(!p.units.some(x=>x.id===unitId&&x.active))throw new ValidationError('Barcode unit must be an active unit owned by this product');const b=await this.persistence(()=>this.repository.addBarcode(context.companyId,productId,unitId,this.domain(()=>normalizeBarcodeDraft(input))));await this.audit('product.barcode-created',context,productId,undefined,b,{barcodeId:b.id});await this.publish('products.product.barcode-changed',await this.get(context.companyId,productId));return b;}
 async updateBarcode(productId:string,barcodeId:string,input:UpdateBarcodeInput,context:ProductMutationContext){const p=await this.get(context.companyId,productId);this.domain(()=>assertProductEditable(p.status));const before=p.barcodes.find(x=>x.id===barcodeId);if(!before)throw new NotFoundError('Product barcode not found');const unitId=input.unitId??before.unitId;if(!p.units.some(x=>x.id===unitId&&x.active))throw new ValidationError('Barcode unit must be an active unit owned by this product');const n=this.domain(()=>normalizeBarcodeDraft({value:input.value??before.value,symbology:hasOwn(input,'symbology')?input.symbology:before.symbology,isPrimary:input.isPrimary??before.isPrimary,active:input.active??before.active,source:hasOwn(input,'source')?input.source:before.source}));const b=await this.persistence(()=>this.repository.updateBarcode(context.companyId,productId,barcodeId,{...n,unitId,expectedVersion:input.version}));await this.audit('product.barcode-updated',context,productId,before,b,{barcodeId});await this.publish('products.product.barcode-changed',await this.get(context.companyId,productId));return b;}
 async deactivateBarcode(productId:string,barcodeId:string,version:number,context:ProductMutationContext){const p=await this.get(context.companyId,productId);const before=p.barcodes.find(x=>x.id===barcodeId&&x.active);if(!before)throw new NotFoundError('Active product barcode not found');const b=await this.persistence(()=>this.repository.deactivateBarcode(context.companyId,productId,barcodeId,version));await this.audit('product.barcode-deactivated',context,productId,before,b,{barcodeId});await this.publish('products.product.barcode-changed',await this.get(context.companyId,productId));return b;}

 listMasters(companyId:string,kind:MasterKind,includeInactive=false){return this.repository.listMasters(companyId,kind,includeInactive);}
 async createMaster(kind:MasterKind,name:string,parentId:string|null,context:ProductMutationContext){const clean=cleanText(name,kind==='manufacturer'||kind==='ingredient'?180:120);if(!clean)throw new ValidationError('Master name is required');const item=await this.persistence(()=>this.repository.createMaster(context.companyId,kind,clean,parentId));await this.audit(`product.${kind}.created`,context,item.id,undefined,item);return item;}
 async updateMaster(kind:MasterKind,id:string,name:string,active:boolean,parentId:string|null,context:ProductMutationContext){const clean=cleanText(name,kind==='manufacturer'||kind==='ingredient'?180:120);if(!clean)throw new ValidationError('Master name is required');const item=await this.persistence(()=>this.repository.updateMaster(context.companyId,kind,id,clean,active,parentId));await this.audit(`product.${kind}.updated`,context,id,undefined,item);return item;}

 async previewBulk(companyId:string,productIds:string[]){const unique=[...new Set(productIds)];const found=await Promise.all(unique.map(id=>this.repository.get(companyId,id)));return{requested:unique.length,matched:found.filter(Boolean).length,missing:unique.filter((_,i)=>!found[i])};}
 async bulkUpdate(productIds:string[],patch:{categoryId?:string|null;manufacturerId?:string|null;status?:ProductStatus;tagIds?:string[]},idempotencyKey:string,context:ProductMutationContext){this.idempotency(idempotencyKey);const unique=[...new Set(productIds)];if(unique.length===0||unique.length>5000)throw new ValidationError('Bulk update requires 1 to 5000 product IDs');const changed=await this.persistence(()=>this.repository.bulkUpdate(context.companyId,unique,patch));await this.audit('product.bulk-update',context,undefined,undefined,{changed},{idempotencyKey,requested:unique.length,patch});return{changed};}

 async startCompanyImport(input:StartCompanyImportInput,idempotencyKey:string,context:ProductMutationContext){this.idempotency(idempotencyKey);const session=await this.repository.startImport({kind:'COMPANY',scopeKey:context.companyId,companyId:context.companyId,idempotencyKey,mode:input.mode,sourceName:input.sourceName??null,sourceId:null,datasetKey:null,mapping:input.mapping??null,totalRows:input.totalRows??null,createdBy:context.actorId});await this.audit('product.import-started',context,session.id,undefined,session);return session;}
 async processCompanyImportChunk(sessionId:string,chunkKey:string,rows:CompanyImportRow[],context:ProductMutationContext){if(rows.length===0||rows.length>500)throw new ValidationError('Import chunk requires 1 to 500 rows');const session=await this.repository.getImportSession(context.companyId,sessionId);if(!session||session.kind!=='COMPANY'||session.companyId!==context.companyId)throw new NotFoundError('Import session not found in authorized company');const claim=await this.repository.claimImportChunk(sessionId,chunkKey);if(!claim.claimed){if(claim.result)return{session,result:claim.result,replayed:true};throw new ConflictError('Import chunk is already processing');}const result=await this.processRows(rows,async row=>{const r=await this.repository.importCompanyRow(sessionId,session.mode,row);return{row:row.row,status:r.status,productId:r.product.id} as ImportChunkResult['rows'][number];});const updated=await this.repository.completeImportChunk(sessionId,claim.id,result);await this.audit('product.import-chunk-completed',context,sessionId,undefined,result,{chunkKey});return{session:updated,result,replayed:false};}
 async getCompanyImportSession(sessionId:string,companyId:string){const s=await this.repository.getImportSession(companyId,sessionId);if(!s||s.companyId!==companyId)throw new NotFoundError('Import session not found in authorized company');return s;}

 async exportCsv(query:Omit<ProductListQuery,'page'|'pageSize'>){const rows=await this.repository.exportList(query);const header=['productCode','productType','displayName','arabicName','englishName','tradeName','manufacturer','category','regulatoryId','atcCode','dosageForm','primaryBarcode','baseUnit','referencePrice','marketStatus','status'];const lines=[header.join(',')];for(const p of rows)lines.push([p.productCode,p.productType,p.displayName,p.arabicName,p.englishName,p.tradeName,p.manufacturer?.name,p.category?.name,p.regulatoryId,p.atcCode,p.dosageForm?.name,p.primaryBarcode,p.baseUnit?.name,p.referencePrice,p.marketStatus,p.status].map(csvCell).join(','));return{fileName:`products-${new Date().toISOString().slice(0,10)}.csv`,contentType:'text/csv;charset=utf-8',content:`\uFEFF${lines.join('\r\n')}`};}
 async exportTable(query:Omit<ProductListQuery,'page'|'pageSize'>){const rows=await this.repository.exportList(query);return{fileName:`products-${new Date().toISOString().slice(0,10)}.xlsx`,sheetName:'Products',headers:['Product Code','Type','Display Name','Arabic Name','English Name','Trade Name','Manufacturer','Category','Regulatory ID','ATC','Dosage Form','Primary Barcode','Base Unit','Reference Price','Market Status','Status'],rows:rows.map(p=>[p.productCode,p.productType,p.displayName,p.arabicName??'',p.englishName??'',p.tradeName??'',p.manufacturer?.name??'',p.category?.name??'',p.regulatoryId??'',p.atcCode??'',p.dosageForm?.name??'',p.primaryBarcode??'',p.baseUnit?.name??'',p.referencePrice??'',p.marketStatus,p.status])};}

 listCentralSources(){return this.repository.listCentralSources();}
 async createCentralSource(input:CentralSourceInput,context:GlobalMutationContext){const normalized=this.source(input);const source=await this.persistence(()=>this.repository.createCentralSource(normalized));await this.globalAudit('central.source-created',context,source.id,undefined,source);return source;}
 async updateCentralSource(id:string,input:CentralSourceInput,context:GlobalMutationContext){const normalized=this.source(input);const source=await this.persistence(()=>this.repository.updateCentralSource(id,normalized));await this.globalAudit('central.source-updated',context,id,undefined,source);return source;}
 centralSearch(query:CentralSearchQuery){return this.repository.centralSearch(query);}
 async getCentral(id:string){const c=await this.repository.getCentral(id);if(!c)throw new NotFoundError('Central drug reference not found');return c;}
 async startCentralImport(input:StartCentralImportInput,idempotencyKey:string,context:GlobalMutationContext){this.idempotency(idempotencyKey);const source=(await this.repository.listCentralSources()).find(x=>x.id===input.sourceId&&x.active);if(!source)throw new ValidationError('Active central source is required');const session=await this.repository.startImport({kind:'CENTRAL',scopeKey:'GLOBAL',companyId:null,idempotencyKey,mode:'CENTRAL_UPSERT_SOURCE_RECORD',sourceName:input.sourceName??source.name,sourceId:input.sourceId,datasetKey:input.datasetKey,mapping:input.mapping??null,totalRows:input.totalRows??null,createdBy:context.actorId});await this.globalAudit('central.ingestion-started',context,session.id,undefined,session,{sourceId:input.sourceId,datasetKey:input.datasetKey,publishedAt:input.publishedAt?.toISOString()??null});return session;}
 async processCentralImportChunk(sessionId:string,chunkKey:string,rows:CentralImportRow[],publishedAt:Date|null,context:GlobalMutationContext){if(rows.length===0||rows.length>500)throw new ValidationError('Central import chunk requires 1 to 500 rows');const session=await this.repository.getImportSession('GLOBAL',sessionId);if(!session||session.kind!=='CENTRAL'||!session.sourceId||!session.datasetKey)throw new NotFoundError('Central import session not found');const claim=await this.repository.claimImportChunk(sessionId,chunkKey);if(!claim.claimed){if(claim.result)return{session,result:claim.result,replayed:true};throw new ConflictError('Central import chunk is already processing');}const importContext:CentralImportContext={sourceId:session.sourceId,datasetKey:session.datasetKey,publishedAt,actorId:context.actorId};const result=await this.processRows(rows,async row=>{this.validateCentralRow(row);const r=await this.repository.importCentralRow(sessionId,importContext,row);return{row:row.row,status:r.status,centralDrugId:r.central.id,reason:r.reason} as ImportChunkResult['rows'][number];});const updated=await this.repository.completeImportChunk(sessionId,claim.id,result);await this.globalAudit('central.ingestion-chunk-completed',context,sessionId,undefined,result,{chunkKey,sourceId:session.sourceId,datasetKey:session.datasetKey});return{session:updated,result,replayed:false};}

 async adoptCentral(centralId:string,idempotencyKey:string,context:ProductMutationContext){this.idempotency(idempotencyKey);const replay=await this.repository.findByCreateRequestKey(context.companyId,idempotencyKey);if(replay)return{product:replay,replayed:true};const central=await this.getCentral(centralId);if(central.status!=='ACTIVE')throw new InvariantViolationError('Only active trusted central references can be adopted');const id=randomUUID();const product=await this.persistence(()=>this.repository.adoptCentral(context.companyId,centralId,id,`PRD-${id.replaceAll('-','').slice(0,10).toUpperCase()}`,idempotencyKey));await this.audit('central.reference-adopted',context,product.id,undefined,product,{centralId});await this.publish('products.central-reference.adopted',product);return{product,replayed:false};}
 async compareCentral(productId:string,context:ProductMutationContext){const comparison=await this.repository.compareCentral(context.companyId,productId);if(!comparison)throw new NotFoundError('Linked product or central reference not found');return comparison;}
 async applyCentral(productId:string,version:number,sections:CentralApplySection[],context:ProductMutationContext){if(sections.length===0)throw new ValidationError('Select at least one central-reference section to apply');const before=await this.get(context.companyId,productId);const product=await this.persistence(()=>this.repository.applyCentral(context.companyId,productId,version,[...new Set(sections)]));await this.audit('central.reference-update-applied',context,productId,before,product,{sections:[...new Set(sections)]});await this.publish('products.product.updated',product);return product;}

 private async processRows<T extends {row:number}>(rows:T[],worker:(row:T)=>Promise<ImportChunkResult['rows'][number]>):Promise<ImportChunkResult>{const out:ImportChunkResult['rows']=[];for(let offset=0;offset<rows.length;offset+=10){const batch=rows.slice(offset,offset+10);const batchResults=await Promise.all(batch.map(async row=>{try{return await worker(row);}catch(error){return{row:row.row,status:'REJECTED',reason:error instanceof Error?error.message:'Rejected'} as const;}}));out.push(...batchResults);}return{accepted:out.filter(x=>x.status==='ACCEPTED').length,updated:out.filter(x=>x.status==='UPDATED').length,rejected:out.filter(x=>x.status==='REJECTED').length,quarantined:out.filter(x=>x.status==='QUARANTINED').length,rows:out};}
 private source(input:CentralSourceInput):CentralSourceInput{const sourceKey=cleanText(input.sourceKey,120);const name=cleanText(input.name,200);const provenance=cleanText(input.provenance,4000);if(!sourceKey||!name||!provenance)throw new ValidationError('Source key, name and provenance are required');return{sourceKey:normalizeSearchText(sourceKey).replace(/\s+/g,'-'),name,provenance,licenseNote:cleanText(input.licenseNote,4000),sourceUrl:cleanText(input.sourceUrl,500),active:input.active};}
 private validateCentralRow(row:CentralImportRow){if(!cleanText(row.sourceRecordKey,180)||!cleanText(row.canonicalName,220))throw new ValidationError('Central row requires sourceRecordKey and canonicalName');if(row.barcode)this.domain(()=>normalizeBarcode(row.barcode));if(row.referencePrice!=null&&(!/^\d+(?:\.\d{1,4})?$/.test(row.referencePrice)||Number(row.referencePrice)<0))throw new ValidationError('Central reference price is invalid');}
 private activationWithExistingUnits(draft:ReturnType<typeof normalizeProductDraft>,product:ProductDetail){const hydrated={...draft,units:product.units.filter(x=>x.active).map((x,i)=>normalizeUnitDraft({name:x.name,shortLabel:x.shortLabel,conversionFactor:x.conversionFactor,isBase:x.isBase,defaultSale:x.defaultSale,defaultPurchase:x.defaultPurchase,active:x.active},i))};this.domain(()=>assertActivationReady(hydrated));}
 private toDraft(p:ProductDetail):ProductDraftInput{return{productType:p.productType,displayName:p.displayName,arabicName:p.arabicName,englishName:p.englishName,tradeName:p.tradeName,description:p.description,notes:p.notes,categoryId:p.category?.id??null,tagIds:p.tags.map(x=>x.id),manufacturerId:p.manufacturer?.id??null,countryOfOrigin:p.countryOfOrigin,dosageFormId:p.dosageForm?.id??null,routeId:p.route?.id??null,regulatoryId:p.regulatoryId,atcCode:p.atcCode,prescriptionClass:p.prescriptionClass,controlled:p.controlled,coldChain:p.coldChain,storageNotes:p.storageNotes,marketStatus:p.marketStatus,referencePrice:p.referencePrice,referencePriceSource:p.referencePriceSource,referencePriceVerifiedAt:p.referencePriceVerifiedAt,imageFileId:p.imageFileId,ingredients:p.ingredients.map(x=>({ingredientId:x.ingredient.id,strengthValue:x.strengthValue,strengthUnit:x.strengthUnit,sortOrder:x.sortOrder})),units:p.units.map(x=>({name:x.name,shortLabel:x.shortLabel,conversionFactor:x.conversionFactor,isBase:x.isBase,defaultSale:x.defaultSale,defaultPurchase:x.defaultPurchase,active:x.active})),barcodes:[]};}
 private summary(p:ProductDetail):ProductSummary{const{description:_description,notes:_notes,countryOfOrigin:_country,storageNotes:_storage,tags:_tags,ingredients:_ingredients,units:_units,barcodes:_barcodes,centralSnapshot:_snapshot,...summary}=p;return summary;}
 private idempotency(value:string){if(value.length<8||value.length>120)throw new ValidationError('Idempotency-Key must contain 8 to 120 characters');}
 private domain<T>(work:()=>T):T{try{return work();}catch(error){if(error instanceof ProductDomainError)throw new ValidationError(error.message,{domainCode:error.code});throw error;}}
 private async persistence<T>(work:()=>Promise<T>):Promise<T>{try{return await work();}catch(error){if(error instanceof ProductConcurrentUpdateError)throw new ConflictError('Product changed by another request; reload before saving');if(error instanceof ProductPersistenceConflictError)throw new ConflictError(error.message||'Product data conflicts with an existing record');if(error instanceof ProductClassificationError)throw new ValidationError(error.message||'Product classification reference is invalid');throw error;}}
 private async audit(action:string,context:ProductMutationContext,entityId:string|undefined,before?:unknown,after?:unknown,metadata?:Record<string,unknown>){const event:AuditRequestedEvent={type:'platform.audit.requested',occurredAt:new Date().toISOString(),actorId:context.actorId,companyId:context.companyId,branchId:context.branchId,entityType:'product',entityId,action,before,after,metadata,requestId:context.requestId};await this.events.publish(event);}
 private async globalAudit(action:string,context:GlobalMutationContext,entityId:string|undefined,before?:unknown,after?:unknown,metadata?:Record<string,unknown>){const event:AuditRequestedEvent={type:'platform.audit.requested',occurredAt:new Date().toISOString(),actorId:context.actorId,entityType:'central-drug-reference',entityId,action,before,after,metadata,requestId:context.requestId};await this.events.publish(event);}
 private async publish(type:ProductChangedEvent['type'],product:ProductDetail){const event:ProductChangedEvent={type,occurredAt:new Date().toISOString(),companyId:product.companyId,productId:product.id,status:product.status};await this.events.publish(event);}
}
